# Generated by Django 4.2 on 2025-12-03 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Staff', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('total_shifts', models.IntegerField(default=0, verbose_name='Tổng số ca')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tổng giờ làm')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Giờ OT')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lương cơ bản')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lương OT')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Thưởng')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Khấu trừ')),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tổng lương')),
                ('status', models.CharField(choices=[('pending', 'Chờ tính toán'), ('calculated', 'Đã tính toán'), ('reviewed', 'Đã xem xét'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên cấu hình')),
                ('payment_type', models.CharField(choices=[('hourly', 'Theo giờ'), ('shift', 'Theo ca'), ('monthly', 'Cố định tháng')], default='hourly', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương/giờ (VNĐ)')),
                ('shift_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Lương/ca (VNĐ)')),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Lương tháng (VNĐ)')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='Hệ số OT')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Số tiền thanh toán')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank', 'Chuyển khoản'), ('momo', 'Ví MoMo'), ('zalopay', 'ZaloPay')], default='cash', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Staff.employeesalary')),
            ],
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Staff.salaryconfig', verbose_name='Cấu hình lương'),
        ),
        migrations.AlterUniqueTogether(
            name='employeesalary',
            unique_together={('employee', 'month', 'year')},
        ),
    ]
