# Generated by Django 4.2 on 2025-12-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Staff', '0003_employeesalary_salaryconfig_salarypayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='base_salary',
            field=models.DecimalField(decimal_places=0, default=20000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salaryconfig',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
