# Generated by Django 4.2 on 2025-09-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Chủ quán'), ('staff', 'Nhân viên'), ('customer', 'Khách hàng')], default='customer', max_length=10),
        ),
    ]
