# Generated by Django 4.2 on 2025-12-04 21:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên ca')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Số lượng nhân viên')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'db_table': 'shifts_shift',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày làm việc')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian đăng ký')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Shifts.shift', verbose_name='Ca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Đăng ký ca',
                'verbose_name_plural': 'Đăng ký ca',
                'db_table': 'shifts_shiftregistration',
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'shift', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssignedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày làm việc')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phân công')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='Shifts.shift', verbose_name='Ca')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Ca đã phân công',
                'verbose_name_plural': 'Ca đã phân công',
                'db_table': 'shifts_assignedshift',
                'ordering': ['date', 'shift__start_time'],
                'unique_together': {('user', 'shift', 'date')},
            },
        ),
    ]
