# Generated by Django 4.2 on 2025-12-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='Sức chứa'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(verbose_name='Ngày làm việc'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên ca'),
        ),
        migrations.AlterModelTable(
            name='shift',
            table=None,
        ),
    ]
