# Generated by Django 4.2 on 2025-12-04 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shifts', '0002_alter_shift_options_alter_shift_capacity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftregistration',
            options={'ordering': ['date', 'shift__start_time']},
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Shifts.shift'),
        ),
        migrations.AlterField(
            model_name='shiftregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='shiftregistration',
            table=None,
        ),
    ]
