# Generated by Django 4.2 on 2025-09-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='type',
            field=models.CharField(choices=[('supply', 'Vật tư'), ('ingredient', 'Nguyên liệu')], default='supply', max_length=16),
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.supply')),
            ],
        ),
    ]
