# Generated by Django 4.2 on 2025-12-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=50, unique=True)),
                ('staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shift_name', models.CharField(blank=True, max_length=100, null=True)),
                ('table_number', models.IntegerField()),
                ('customer_count', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ'), ('transfer', 'Chuyển khoản'), ('momo', 'Momo'), ('zalopay', 'ZaloPay')], max_length=50)),
                ('status', models.CharField(choices=[('paid', 'Đã thanh toán'), ('pending', 'Chờ thanh toán'), ('cancelled', 'Đã hủy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_bills', models.IntegerField(default=0)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('digital_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_bill_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Doanh thu hàng ngày',
                'verbose_name_plural': 'Doanh thu hàng ngày',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(default='Đồ uống', max_length=100)),
                ('current_stock', models.IntegerField()),
                ('min_stock', models.IntegerField(default=10)),
                ('status', models.CharField(choices=[('normal', 'Bình thường'), ('low', 'Sắp hết'), ('out', 'Hết hàng')], default='normal', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Báo cáo tồn kho',
                'verbose_name_plural': 'Báo cáo tồn kho',
                'ordering': ['status', 'product_category', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(default='Đồ uống', max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Reports.bill')),
            ],
        ),
    ]
