/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.Bill_DAO;
import DAO.Haohut_DAO;
import DAO.Nhanvien_DAO;
import DAO.Nhapnguyenlieu_DAO;
import DAO.Order_DAO;
import Lop.Bill;
import Lop.Haohut;
import Lop.Nhapnguyenlieu;
import Lop.Order;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_Thongke extends javax.swing.JFrame {

    /**
     * Creates new form Form_Thongke
     */
    public Form_Thongke() {
        initComponents();
        Bill_DAO bill = new Bill_DAO();
        List<Bill> list_bill =bill.selectAll();
        loadTableBill(list_bill);
        Nhapnguyenlieu_DAO nhap= new Nhapnguyenlieu_DAO();             
        List<Nhapnguyenlieu> list_nhap = nhap.selectAll();
        loadTableNhapnguyenlieu(list_nhap);
        Haohut_DAO hao = new Haohut_DAO();
        List<Haohut> list_hao = hao.selectAll();
        loadTableHaohut(list_hao);
    }
   
    private void loadTableBill(List<Bill> list) {
    DefaultTableModel model = (DefaultTableModel) table_bill.getModel();
    model.setRowCount(0);

    double tong = 0;
    for (Bill b : list) {
        model.addRow(new Object[]{
            b.getMa_Bill(),
            b.getMa_NV(),
            b.getTongGia(),
            b.getBan(),
            b.getDate_Bill()
            
        });
        if ("Đã thanh toán".equalsIgnoreCase(b.getTrangThai())) {
            tong += b.getTongGia();
        }
    }
    Label_tongtien_bill.setText( tong + " VNĐ");
}
    private void loadTableNhapnguyenlieu(List<Nhapnguyenlieu> list) {
    DefaultTableModel model = (DefaultTableModel) table_nhapnguyenlieu.getModel();
    model.setRowCount(0);

    double tong = 0;
    for (Nhapnguyenlieu nl : list) {
        model.addRow(new Object[]{
            nl.getMaNhap(),
            nl.getMaNguyenlieu(),
            nl.getSoLuong(),
            nl.getGia(),
            nl.getTongTien(),
            nl.getNgayNhap()
        });
        tong += nl.getSoLuong() * nl.getGia();
    }
    Label_tongtien_nhapnglieu.setText( tong + " VNĐ");
}
    private void loadTableHaohut(List<Haohut> list) {
    DefaultTableModel model = (DefaultTableModel) table_hoahut.getModel();
    model.setRowCount(0);

    double tong = 0;
    for (Haohut h : list) {
        model.addRow(new Object[]{
            h.getMa_Hao(),
            h.getMa_Vattu(),            
            h.getSL_VT(),
            h.getGia_VT(),
            h.getTonggia_VT(),
            h.getdate_invt()
        });
        tong += h.getTonggia_VT();
    }
    Label_tongtien_haophi.setText( tong + " VNĐ");
}
    private void loadTableChitiethoadon(List<Order> list) {
    DefaultTableModel model = (DefaultTableModel) table_chitiethoadon.getModel();
    model.setRowCount(0);

    for (Order ct : list) {
        Object[] row = new Object[] {
            ct.getMa_Bill(),
            ct.getMa_Mon(),
            ct.getSL_order(),
            ct.gettonggia_order()
        };
        model.addRow(row);
    }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_bill = new javax.swing.JTable();
        combobox_ngay = new javax.swing.JComboBox<>();
        combobox_thang = new javax.swing.JComboBox<>();
        combobox_nam = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_search_manv = new javax.swing.JTextField();
        but_search_ma_nv = new javax.swing.JButton();
        but_search_theongay = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_chitiethoadon = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Label_tongtien_bill = new javax.swing.JLabel();
        but_search_theothang = new javax.swing.JButton();
        but_search_tatca = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_hoahut = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Label_tongtien_haophi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_nhapnguyenlieu = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        Label_tongtien_nhapnglieu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Thống kê");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        table_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Mã nhân viên", "Tổng tiền", "Bàn", "Thời gian"
            }
        ));
        table_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_bill);

        combobox_ngay.setMaximumRowCount(32);
        combobox_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        combobox_ngay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_ngayActionPerformed(evt);
            }
        });

        combobox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        combobox_nam.setMaximumRowCount(50);
        combobox_nam.setModel(new javax.swing.DefaultComboBoxModel<String>(
            java.util.stream.IntStream.rangeClosed(2000, java.time.Year.now().getValue())
            .mapToObj(String::valueOf)
            .toArray(String[]::new)
        )

    );
    combobox_nam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            combobox_namActionPerformed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel2.setText("Mã nhân viên :");

    txt_search_manv.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txt_search_manvActionPerformed(evt);
        }
    });

    but_search_ma_nv.setBackground(new java.awt.Color(102, 255, 255));
    but_search_ma_nv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_ma_nv.setText("Tìm mã nhân viên");
    but_search_ma_nv.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_ma_nvActionPerformed(evt);
        }
    });

    but_search_theongay.setBackground(new java.awt.Color(102, 255, 255));
    but_search_theongay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_theongay.setText("Tìm theo ngày");
    but_search_theongay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_theongayActionPerformed(evt);
        }
    });

    table_chitiethoadon.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Mã món", "Số lượng", "Giá", "Thành tiền"
        }
    ));
    jScrollPane2.setViewportView(table_chitiethoadon);

    jLabel5.setBackground(new java.awt.Color(204, 204, 204));
    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel5.setText("Chi tiết hoá đơn");

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel10.setText("Tổng doanh thu :");

    Label_tongtien_bill.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    but_search_theothang.setBackground(new java.awt.Color(102, 255, 255));
    but_search_theothang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_theothang.setText("Tìm theo tháng");
    but_search_theothang.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_theothangActionPerformed(evt);
        }
    });

    but_search_tatca.setBackground(new java.awt.Color(102, 255, 255));
    but_search_tatca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_tatca.setText("Tìm tất cả");
    but_search_tatca.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_tatcaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(160, 160, 160)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Label_tongtien_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                        .addComponent(combobox_ngay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txt_search_manv))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(but_search_ma_nv, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(but_search_theongay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(but_search_theothang, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addComponent(but_search_tatca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(20, 20, 20))))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(combobox_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(but_search_theongay)
                .addComponent(but_search_theothang))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(but_search_tatca))
                .addComponent(but_search_ma_nv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_tongtien_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
            .addGap(78, 78, 78))
    );

    jPanel4.setBackground(new java.awt.Color(204, 204, 204));

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel6.setText("Hao hụt");

    table_hoahut.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã hao hụt", "Mã vật tư", "Số lượng", "Giá", "Thành tiền", "Ngày nhập"
        }
    ));
    jScrollPane3.setViewportView(table_hoahut);

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel7.setText("Tổng phí hao :");

    Label_tongtien_haophi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel9.setText("Nguyên liệu mua vào");

    table_nhapnguyenlieu.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã mua", "Mã nguyên liệu", "Số lượng ", "Giá", "Thành tiền", "Ngày nhập"
        }
    ));
    jScrollPane4.setViewportView(table_nhapnguyenlieu);

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel12.setText("Tổng tiền nhập nguyên liệu :");

    Label_tongtien_nhapnglieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(54, 54, 54)
                            .addComponent(Label_tongtien_haophi, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(134, 134, 134)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Label_tongtien_nhapnglieu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 5, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(216, 216, 216)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(Label_tongtien_haophi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGap(24, 24, 24)
                    .addComponent(jLabel12))
                .addComponent(Label_tongtien_nhapnglieu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(21, 21, 21))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_manvActionPerformed

    private void combobox_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_namActionPerformed

    private void combobox_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_ngayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_ngayActionPerformed

    private void but_search_theongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_theongayActionPerformed
           try {
        int ngay = Integer.parseInt(combobox_ngay.getSelectedItem().toString());
        int thang = Integer.parseInt(combobox_thang.getSelectedItem().toString()) - 1; // Tháng trong Java bắt đầu từ 0
        int nam = Integer.parseInt(combobox_nam.getSelectedItem().toString());

        Calendar calendar = Calendar.getInstance();
        calendar.set(nam, thang, ngay);
        java.util.Date date = calendar.getTime();
        

        Bill_DAO dao = new Bill_DAO();
        List<Bill> list = dao.selectByDate(date);
        loadTableBill(list); // Phương thức đổ dữ liệu ra bảng'
        
        Nhapnguyenlieu_DAO nhap= new Nhapnguyenlieu_DAO();             
        List<Nhapnguyenlieu> list_nhap = nhap.selectByDate(date);
        loadTableNhapnguyenlieu(list_nhap);
        Haohut_DAO hao = new Haohut_DAO();
        List<Haohut> list_hao = hao.selectByDate(date);
        loadTableHaohut(list_hao);
        
        

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày hợp lệ!");
    }
    }//GEN-LAST:event_but_search_theongayActionPerformed

    private void but_search_theothangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_theothangActionPerformed
        // TODO add your handling code here:
        try {
        int thang = Integer.parseInt(combobox_thang.getSelectedItem().toString());
        int nam = Integer.parseInt(combobox_nam.getSelectedItem().toString());

        // Bill
        Bill_DAO billDAO = new Bill_DAO();
        List<Bill> billList = billDAO.selectByMonth(thang, nam);
        loadTableBill(billList);

        // Nhập nguyên liệu
        Nhapnguyenlieu_DAO nlDAO = new Nhapnguyenlieu_DAO();
        List<Nhapnguyenlieu> nlList = nlDAO.selectByMonthYear(thang, nam);
        loadTableNhapnguyenlieu(nlList);

        // Hao hụt
        Haohut_DAO haoDAO = new Haohut_DAO();
        List<Haohut> haoList = haoDAO.selectByMonthYear(thang, nam);
        loadTableHaohut(haoList);

    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_but_search_theothangActionPerformed

    private void but_search_tatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_tatcaActionPerformed
        // TODO add your handling code here:
         Bill_DAO billDAO = new Bill_DAO();
    Nhapnguyenlieu_DAO nlDAO = new Nhapnguyenlieu_DAO();
    Haohut_DAO haoDAO = new Haohut_DAO();

    loadTableBill(billDAO.selectAll());
    loadTableNhapnguyenlieu(nlDAO.selectAll());
    loadTableHaohut(haoDAO.selectAll());
    }//GEN-LAST:event_but_search_tatcaActionPerformed

    private void table_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_billMouseClicked
     int selectedRow = table_bill.getSelectedRow();
    if (selectedRow >= 0) {
        // Lấy mã bill dạng String
        String maBill = table_bill.getValueAt(selectedRow, 0).toString();

        // Gọi DAO để lấy chi tiết hóa đơn
        Order_DAO dao = new Order_DAO();
        List<Order> list = dao.selectByMaBill(maBill);

        // Hiển thị lên bảng chi tiết hóa đơn
        loadTableChitiethoadon(list);
    }
    }//GEN-LAST:event_table_billMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Form_Main nv = new Form_Main();
                    nv.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void but_search_ma_nvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_ma_nvActionPerformed
        // TODO add your handling code here:
        String maNV = txt_search_manv.getText().trim(); // Lấy dữ liệu người dùng nhập

    if (maNV.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên để tìm kiếm.");
        return;
    }

    Bill_DAO billDAO = new Bill_DAO();
    List<Bill> list = billDAO.selectByMaNV(maNV);

    if (list.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn nào của nhân viên này.");
    }

    loadTableBill(list); // Hiển thị danh sách hóa đơn tìm được lên bảng
    }//GEN-LAST:event_but_search_ma_nvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Thongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Thongke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_tongtien_bill;
    private javax.swing.JLabel Label_tongtien_haophi;
    private javax.swing.JLabel Label_tongtien_nhapnglieu;
    private javax.swing.JButton but_search_ma_nv;
    private javax.swing.JButton but_search_tatca;
    private javax.swing.JButton but_search_theongay;
    private javax.swing.JButton but_search_theothang;
    private javax.swing.JComboBox<String> combobox_nam;
    private javax.swing.JComboBox<String> combobox_ngay;
    private javax.swing.JComboBox<String> combobox_thang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_bill;
    private javax.swing.JTable table_chitiethoadon;
    private javax.swing.JTable table_hoahut;
    private javax.swing.JTable table_nhapnguyenlieu;
    private javax.swing.JTextField txt_search_manv;
    // End of variables declaration//GEN-END:variables
}
