/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.LoaiMon_DAO;
import DAO.Mon_DAO;
import Lop.LoaiMon;
import Lop.Mon;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_Sanpham extends javax.swing.JFrame {
 
    /**
     * Creates new form Form_Sanpham
     */
    public Form_Sanpham() {
        initComponents();
        loadTableMon();
        loadTableLoaiMon();
    
    }
    public void loadTableMon() {
    Mon_DAO dao = new Mon_DAO();
    List<Mon> list = dao.selectAll();
    DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
    model.setRowCount(0);
    for (Mon mon : list) {
        model.addRow(new Object[]{
            mon.getMa_Mon(), mon.getTen_Mon(), mon.getGia_Mon(), mon.getMa_LM(), mon.getHinhanh()
        });
    }
}
    public void loadTableLoaiMon() {
    LoaiMon_DAO dao = new LoaiMon_DAO();
    List<LoaiMon> list = dao.selectAll();
    DefaultTableModel model = (DefaultTableModel) table_loaimon.getModel();
    model.setRowCount(0);
    for (LoaiMon lm : list) {
        model.addRow(new Object[]{
            lm.getMa_LM(), lm.getTen_LM()
        });
    }
}
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_mon = new javax.swing.JTable();
        txt_search_loaimon_chomon = new javax.swing.JTextField();
        but_timloaimon_chomon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        but_them_mon = new javax.swing.JButton();
        but_xoa_mon = new javax.swing.JButton();
        but_updatemon = new javax.swing.JButton();
        label_anh_mon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tenmon = new javax.swing.JTextField();
        txt_hinhanh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_loaimon = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_loaimon = new javax.swing.JTable();
        Search_loaimon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Ma_Loaimon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Ten_loaimon = new javax.swing.JTextField();
        but_themloaimon = new javax.swing.JButton();
        but_xoaloaimon = new javax.swing.JButton();
        but_capnhatloaimon = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        search_loaimon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_mamon = new javax.swing.JTextField();
        but_timmamon = new javax.swing.JButton();
        txt_searchmamon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jPanel3.setBackground(new java.awt.Color(102, 255, 255));

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(102, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Menu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton2)
                .addGap(421, 421, 421)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(399, 399, 399))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButton2)
                .addContainerGap(39, Short.MAX_VALUE))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        table_mon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Giá cả", "Thể loại", "Ảnh"
            }
        ));
        table_mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_monMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_mon);

        but_timloaimon_chomon.setBackground(new java.awt.Color(153, 255, 255));
        but_timloaimon_chomon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_timloaimon_chomon.setText("Tìm");
        but_timloaimon_chomon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timloaimon_chomonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Hình ảnh :");

        txt_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giaActionPerformed(evt);
            }
        });

        but_them_mon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_them_mon.setText("Thêm ");
        but_them_mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_them_monActionPerformed(evt);
            }
        });

        but_xoa_mon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_xoa_mon.setText("Xoá");
        but_xoa_mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoa_monActionPerformed(evt);
            }
        });

        but_updatemon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_updatemon.setText("Cập nhật");
        but_updatemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_updatemonActionPerformed(evt);
            }
        });

        label_anh_mon.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tên món :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Giá cả :");

        txt_hinhanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hinhanhActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Thể loại :");

        txt_loaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_loaimonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        table_loaimon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại", "Tên loại"
            }
        ));
        table_loaimon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_loaimonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_loaimon);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã loại :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tên loại :");

        but_themloaimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_themloaimon.setText("Thêm");
        but_themloaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_themloaimonActionPerformed(evt);
            }
        });

        but_xoaloaimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_xoaloaimon.setText("Xoá");
        but_xoaloaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoaloaimonActionPerformed(evt);
            }
        });

        but_capnhatloaimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_capnhatloaimon.setText("Cập nhật");
        but_capnhatloaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhatloaimonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Loại món :");

        search_loaimon.setBackground(new java.awt.Color(102, 255, 255));
        search_loaimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search_loaimon.setText("Tìm");
        search_loaimon.setToolTipText("");
        search_loaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_loaimonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search_loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_loaimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ma_Loaimon))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(but_themloaimon))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(but_xoaloaimon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(but_capnhatloaimon))
                                    .addComponent(Ten_loaimon))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search_loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_loaimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ma_Loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ten_loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_themloaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_xoaloaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_capnhatloaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã món :");

        but_timmamon.setBackground(new java.awt.Color(153, 255, 255));
        but_timmamon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_timmamon.setText("Tìm");
        but_timmamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timmamonActionPerformed(evt);
            }
        });

        txt_searchmamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchmamonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã loại :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Mã món :");

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Tât cả");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(but_them_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(but_xoa_mon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(but_updatemon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_searchmamon, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_search_loaimon_chomon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(but_timloaimon_chomon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(but_timmamon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                .addGap(19, 19, 19)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_anh_mon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txt_hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenmon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mamon, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mamon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_loaimon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_anh_mon, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addGap(78, 78, 78))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_loaimon_chomon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_timloaimon_chomon)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_timmamon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_searchmamon)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_updatemon)
                    .addComponent(but_xoa_mon)
                    .addComponent(but_them_mon))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_timloaimon_chomonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timloaimon_chomonActionPerformed
       String maMon = txt_search_loaimon_chomon.getText().trim();
    if (maMon.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã loại để tìm!");
        return;
    }
    DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
    model.setRowCount(0); // Xóa dòng cũ

    Mon_DAO dao = new Mon_DAO();
    List<Mon> list = dao.selectByMaLoai(maMon);

    for (Mon m : list) {
        Object[] row = new Object[] {
            m.getMa_Mon(),
            m.getTen_Mon(),
            m.getGia_Mon(),
            m.getMa_LM(),
            m.getHinhanh()
        };
        model.addRow(row);
    }
   
    }//GEN-LAST:event_but_timloaimon_chomonActionPerformed

    private void but_them_monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_them_monActionPerformed
    String ma = txt_mamon.getText();
    String ten = txt_tenmon.getText();
    String giaStr = txt_gia.getText();
    String maLM = txt_loaimon.getText();
    String hinh = txt_hinhanh.getText();

    if (ma.isEmpty() || ten.isEmpty() || giaStr.isEmpty() || maLM.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin món!");
        return;
    }

    LoaiMon_DAO loaiDao = new LoaiMon_DAO();
    if (!loaiDao.existsById(maLM)) {
        JOptionPane.showMessageDialog(this, "Loại món không tồn tại! Vui lòng kiểm tra lại mã loại món.");
        return;
    }

    try {
        double gia = Double.parseDouble(giaStr);
        Mon_DAO dao = new Mon_DAO();
        dao.Insert(new Mon(ma, ten, gia, maLM, hinh));
        JOptionPane.showMessageDialog(this, "Thêm món thành công!");
        loadTableMon();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá món phải là số!");
    }
    }//GEN-LAST:event_but_them_monActionPerformed

    private void but_xoa_monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoa_monActionPerformed
    String ma = txt_mamon.getText().trim();
    if (ma.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã món cần xóa!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa món này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        Mon_DAO dao = new Mon_DAO();
        dao.Delete(ma);
        JOptionPane.showMessageDialog(this, "Xóa món thành công!");
        loadTableMon();
        
    }
    }//GEN-LAST:event_but_xoa_monActionPerformed

    private void but_updatemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_updatemonActionPerformed
       String ma = txt_mamon.getText();
    String ten = txt_tenmon.getText();
    String giaStr = txt_gia.getText();
    String maLM = txt_loaimon.getText();
    String hinh = txt_hinhanh.getText();

    if (ma.isEmpty() || ten.isEmpty() || giaStr.isEmpty() || maLM.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin món!");
        return;
    }

    LoaiMon_DAO loaiDao = new LoaiMon_DAO();
    if (!loaiDao.existsById(maLM)) {
        JOptionPane.showMessageDialog(this, "Loại món không tồn tại! Vui lòng kiểm tra lại mã loại món.");
        return;
    }

    try {
        double gia = Double.parseDouble(giaStr);
        Mon_DAO dao = new Mon_DAO();
        dao.Insert(new Mon(ma, ten, gia, maLM, hinh));
        JOptionPane.showMessageDialog(this, "Thêm món thành công!");
        loadTableMon();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá món phải là số!");
    }
    }//GEN-LAST:event_but_updatemonActionPerformed

    private void txt_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giaActionPerformed

    private void txt_hinhanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hinhanhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hinhanhActionPerformed

    private void txt_loaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_loaimonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_loaimonActionPerformed

    private void but_themloaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themloaimonActionPerformed
   String ma = Ma_Loaimon.getText();
    String ten = Ten_loaimon.getText();
    
    if (ma.isEmpty() || ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin loại món!");
        return;
    }

    LoaiMon_DAO dao = new LoaiMon_DAO();
    LoaiMon lm = new LoaiMon(ma, ten);
    dao.insert(lm);
    JOptionPane.showMessageDialog(this, "Thêm loại món thành công!");
     loadTableLoaiMon();
    }//GEN-LAST:event_but_themloaimonActionPerformed

    private void but_xoaloaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaloaimonActionPerformed
            String ma = Ma_Loaimon.getText();
    if (ma.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã loại món cần xóa!");
        return;
    }

    LoaiMon_DAO dao = new LoaiMon_DAO();
    dao.delete(ma);
    JOptionPane.showMessageDialog(this, "Xóa loại món thành công!");
     loadTableLoaiMon();
    }//GEN-LAST:event_but_xoaloaimonActionPerformed

    private void but_capnhatloaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhatloaimonActionPerformed
      String ma = Ma_Loaimon.getText();
    String ten = Ten_loaimon.getText();

    if (ma.isEmpty() || ten.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã và tên loại món!");
        return;
    }

    LoaiMon_DAO dao = new LoaiMon_DAO();
    dao.update(new LoaiMon(ma, ten));
    JOptionPane.showMessageDialog(this, "Cập nhật loại món thành công!");
     loadTableLoaiMon();
    }//GEN-LAST:event_but_capnhatloaimonActionPerformed

    private void search_loaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_loaimonActionPerformed
    String keyword = Search_loaimon.getText();
    LoaiMon_DAO dao = new LoaiMon_DAO();
    List<LoaiMon> list = dao.selectByName(keyword);  // dùng hàm bạn có thể thêm ở DAO

    DefaultTableModel model = (DefaultTableModel) table_loaimon.getModel();
    model.setRowCount(0);
    for (LoaiMon lm : list) {
        model.addRow(new Object[]{lm.getMa_LM(), lm.getTen_LM()});
    }
    }//GEN-LAST:event_search_loaimonActionPerformed

    private void but_timmamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timmamonActionPerformed
        // TODO add your handling code here: 
        String maMon = txt_searchmamon.getText().trim();
    if (maMon.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã món để tìm!");
        return;
    }

    Mon_DAO dao = new Mon_DAO();
    Mon mon = dao.selectByMa_Mon(maMon);

    DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    if (mon != null) {
        model.addRow(new Object[]{
            mon.getMa_Mon(),
            mon.getTen_Mon(),
            mon.getGia_Mon(),
            mon.getMa_LM(),
            mon.getHinhanh()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy món!");
    }
    }//GEN-LAST:event_but_timmamonActionPerformed

    private void table_monMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_monMouseClicked
        // TODO add your handling code here:
        int row = table_mon.getSelectedRow();
        if (row >= 0) {
            txt_mamon.setText(table_mon.getValueAt(row, 0).toString());
            txt_tenmon.setText(table_mon.getValueAt(row, 1).toString());
            txt_gia.setText(table_mon.getValueAt(row, 2).toString());
            txt_loaimon.setText(table_mon.getValueAt(row, 3).toString());
            txt_hinhanh.setText(table_mon.getValueAt(row, 4).toString());
            String imagePath= table_mon.getValueAt(row, 4).toString();
            ImageIcon icon = new ImageIcon(imagePath);

        // Resize ảnh cho vừa JLabel
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(label_anh_mon.getWidth(), label_anh_mon.getHeight(), Image.SCALE_SMOOTH);
        label_anh_mon.setIcon(new ImageIcon(scaledImg));
           
        }
    
    }//GEN-LAST:event_table_monMouseClicked

    private void table_loaimonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_loaimonMouseClicked
        // TODO add your handling code here:
         int row = table_loaimon.getSelectedRow();
        if (row >= 0) {
            Ma_Loaimon.setText(table_loaimon.getValueAt(row, 0).toString());
            Ten_loaimon.setText(table_loaimon.getValueAt(row, 1).toString());
        }
    }//GEN-LAST:event_table_loaimonMouseClicked

    private void txt_searchmamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchmamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchmamonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Form_Main nv = new Form_Main();
                    nv.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadTableMon();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Sanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Sanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ma_Loaimon;
    private javax.swing.JTextField Search_loaimon;
    private javax.swing.JTextField Ten_loaimon;
    private javax.swing.JButton but_capnhatloaimon;
    private javax.swing.JButton but_them_mon;
    private javax.swing.JButton but_themloaimon;
    private javax.swing.JButton but_timloaimon_chomon;
    private javax.swing.JButton but_timmamon;
    private javax.swing.JButton but_updatemon;
    private javax.swing.JButton but_xoa_mon;
    private javax.swing.JButton but_xoaloaimon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_anh_mon;
    private javax.swing.JButton search_loaimon;
    private javax.swing.JTable table_loaimon;
    private javax.swing.JTable table_mon;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_hinhanh;
    private javax.swing.JTextField txt_loaimon;
    private javax.swing.JTextField txt_mamon;
    private javax.swing.JTextField txt_search_loaimon_chomon;
    private javax.swing.JTextField txt_searchmamon;
    private javax.swing.JTextField txt_tenmon;
    // End of variables declaration//GEN-END:variables
}
