/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.Ca_DAO;
import DAO.DoiCa_DAO;
import DAO.LichLamViec_DAO;
import static Form.Form_login.role;
import Lop.Ca;
import Lop.DoiCa;
import Lop.LichLamViec;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ADMIN
 */
public class Form_Dangkylamviec extends javax.swing.JFrame {

    /**
     * Creates new form Form_Dangkylamviec
     */
    public Form_Dangkylamviec() {
        initComponents();
        loadTable();
        fillTableDoiCa();
    }
     private void loadTable() {
    try {
        
        Ca_DAO ca_DAO= new Ca_DAO();
        
        List<Ca> list = ca_DAO.selectAll();
        DefaultTableModel model = (DefaultTableModel) table_ca.getModel();
        model.setRowCount(0);
        for (Ca ca : list) {
            model.addRow(new Object[]{
                ca.getMaCa(),
                ca.getNgay().toString(),
                ca.getTimeStart(),
                ca.getTimeEnd(),
                ca.getLuongCa(),
                ca.getSoluongCa(),
                ca.getSoluongDky()
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
   private void hienThiNhanVienTrongCa(String maCa) {
    try {
        LichLamViec_DAO dao = new LichLamViec_DAO();
        List<LichLamViec> danhSach = dao.getByCa(maCa);

        DefaultTableModel model = (DefaultTableModel) table_lamviec.getModel();
        model.setRowCount(0); // Xoá dữ liệu cũ

        for (LichLamViec lich : danhSach) {
            model.addRow(new Object[]{
                lich.getMaPhanLich(),
                lich.getMaNhanVien(),
                lich.getNgay(),
                lich.getCa(),
                lich.getLuong(),
                lich.getTrangThai() == 1 ? "Làm" : "Nghỉ"
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị nhân viên làm việc trong ca: " + e.getMessage());
    }
}
   private void fillTableDoiCa() {
    DefaultTableModel model = (DefaultTableModel) table_doica.getModel();
    model.setRowCount(0);

    try {
        DoiCa_DAO dao = new DoiCa_DAO();
        List<DoiCa> list = dao.selectByMaNV1(Form_login.MaNV);

        for (DoiCa dc : list) {
            String trangThaiText;
            switch (dc.getTrangThai()) {
                case 0: trangThaiText = "Chờ duyệt"; break;
                case 1: trangThaiText = "Đã đồng ý"; break;
                case 2: trangThaiText = "Từ chối"; break;
                default: trangThaiText = "Không rõ"; break;
            }

            model.addRow(new Object[] {
                dc.getMaDoiCa(),
                dc.getMaPhanLich1(),
                dc.getMaPhanLich2(),
                dc.getMaNV1(),
                dc.getMaNV2(),
                trangThaiText
            });
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Lỗi khi load đổi ca: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ca = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Combobox_ngay = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combobox_thang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combobox_nam = new javax.swing.JComboBox<>();
        but_tim_ngay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_maca = new javax.swing.JTextField();
        txt_ngay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_giobatdau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_gioketthuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_luong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sonhanvien = new javax.swing.JTextField();
        but_dangkycalam = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_doica = new javax.swing.JTable();
        but_dongydoica = new javax.swing.JButton();
        but_tuchoidoica = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Label_lich1 = new javax.swing.JLabel();
        Label_lich2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Label_nhanvien1 = new javax.swing.JLabel();
        Label_nhanvien2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Label_madoica = new javax.swing.JLabel();
        but_back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_lamviec = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Label_nv1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txt_lich2 = new javax.swing.JTextField();
        txt_lich1 = new javax.swing.JTextField();
        but_xoaca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Đăng ký lịch làm việc");

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        table_ca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ca", "Ngày", "Giờ bắt đầu", "Giờ kết thúc", "Lương", "Số nhân viên", "Đăng ký"
            }
        ));
        table_ca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_caMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ca);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày :");

        Combobox_ngay.setMaximumRowCount(32);
        Combobox_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tháng :");

        combobox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Năm :");

        combobox_nam.setModel(new javax.swing.DefaultComboBoxModel<String>(
            java.util.stream.IntStream.rangeClosed(2000, java.time.Year.now().getValue())
            .mapToObj(String::valueOf)
            .toArray(String[]::new)
        )

    );
    combobox_nam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            combobox_namActionPerformed(evt);
        }
    });

    but_tim_ngay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_tim_ngay.setText("Tìm");
    but_tim_ngay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_tim_ngayActionPerformed(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel5.setText("Mã ca :");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel6.setText("Ngày :");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel7.setText("Bắt đầu :");

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel8.setText("Kết thúc :");

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel9.setText("Lương :");

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel10.setText("Số người :");

    but_dangkycalam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    but_dangkycalam.setText("Đăng ký ca làm");
    but_dangkycalam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_dangkycalamActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Combobox_ngay, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addGap(19, 19, 19)
                    .addComponent(combobox_thang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(combobox_nam, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(but_tim_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txt_luong))
                                .addComponent(txt_maca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_gioketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_sonhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_giobatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(but_dangkycalam, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(20, 20, 20))
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
            .addGap(19, 19, 19))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(6, 6, 6)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addComponent(Combobox_ngay))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(combobox_thang))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(combobox_nam))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(but_tim_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_maca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addComponent(txt_giobatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_gioketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(txt_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6))
            .addGap(18, 18, 18)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addComponent(txt_sonhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(but_dangkycalam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(25, 25, 25))
    );

    jPanel2.setBackground(new java.awt.Color(251, 228, 255));

    jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel16.setText("Yêu cầu đổi ca");

    table_doica.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã đổi", "Lịch 1", "Lịch 2", "Nhân viên 1", "Nhân viên 2", "Trạng thái"
        }
    ));
    table_doica.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_doicaMouseClicked(evt);
        }
    });
    jScrollPane3.setViewportView(table_doica);

    but_dongydoica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    but_dongydoica.setText("Đồng ý");
    but_dongydoica.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_dongydoicadoicaActionPerformed(evt);
        }
    });

    but_tuchoidoica.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    but_tuchoidoica.setText("Từ chối ");
    but_tuchoidoica.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_tuchoidoicaActionPerformed(evt);
        }
    });

    jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel17.setText("Lịch 1 :");

    jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel18.setText("Lịch 2 :");

    jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel19.setText("Nhân viên 1 :");

    jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel20.setText("Nhân viên 2 :");

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel11.setText("Mã đổi ca :");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGap(97, 97, 97))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(but_dongydoica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(37, 37, 37)
                            .addComponent(but_tuchoidoica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(207, 207, 207))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Label_lich2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Label_lich1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(12, 12, 12)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Label_nhanvien2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(193, 193, 193)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Label_nhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Label_madoica, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(jLabel16)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Label_lich1)
                .addComponent(jLabel19)
                .addComponent(Label_nhanvien1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel18)
                .addComponent(Label_lich2)
                .addComponent(jLabel20)
                .addComponent(Label_nhanvien2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(jLabel22)
                .addComponent(Label_madoica))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(but_dongydoica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_tuchoidoica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    but_back.setBackground(new java.awt.Color(102, 255, 255));
    but_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    but_back.setText("Back");
    but_back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_backActionPerformed(evt);
        }
    });

    jPanel4.setBackground(new java.awt.Color(255, 255, 204));

    table_lamviec.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Mã phân lịch", "Mã nhân viên", "Mã ca", "Ngày", "Lương"
        }
    ));
    table_lamviec.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_lamviecMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(table_lamviec);

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel12.setText("Mã phân lịch 1 :");

    jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel13.setText("Mã phân lịch 2 :");

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel14.setText("Mã nhân viên 1 :");

    Label_nv1.setText("jLabel15");

    jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jButton2.setText("Đổi ca");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    but_xoaca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    but_xoaca.setText("Xoá ca ");
    but_xoaca.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_xoacaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(47, 47, 47))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(62, 62, 62)
                    .addComponent(but_xoaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(76, 76, 76))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_lich1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_lich2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Label_nv1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(jLabel14)
                .addComponent(Label_nv1)
                .addComponent(txt_lich1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(txt_lich2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_xoaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(8, 8, 8))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(but_back, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(315, 315, 315)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, Short.MAX_VALUE)
            .addGap(276, 276, 276))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)
                    .addGap(5, 5, 5))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(but_back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(3, 3, 3))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_caMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_caMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_ca.getSelectedRow();
        if (selectedRow != -1) {
            String maCa = table_ca.getValueAt(selectedRow, 0).toString(); // Cột 0 là mã ca
            hienThiNhanVienTrongCa(maCa);
            txt_maca.setText(table_ca.getValueAt(selectedRow, 0).toString());
            txt_ngay.setText(table_ca.getValueAt(selectedRow, 1).toString());
            txt_giobatdau.setText(table_ca.getValueAt(selectedRow, 2).toString());
            txt_gioketthuc.setText(table_ca.getValueAt(selectedRow, 3).toString());
            txt_luong.setText(table_ca.getValueAt(selectedRow, 4).toString());
            txt_sonhanvien.setText(table_ca.getValueAt(selectedRow, 5).toString());
        }
    }//GEN-LAST:event_table_caMouseClicked

    private void combobox_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_namActionPerformed

    private void but_tim_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_tim_ngayActionPerformed
        // TODO add your handling code here:
        try {
            // Lấy dữ liệu từ ComboBox thay vì TextField
            String nam = combobox_nam.getSelectedItem().toString();
            String thang = combobox_thang.getSelectedItem().toString();
            String ngay = Combobox_ngay.getSelectedItem().toString();

            // Đảm bảo đúng định dạng yyyy-MM-dd
            String ngayStr = nam + "-" + thang + "-" + ngay;
            Date ngay_1 = Date.valueOf(ngayStr); // java.sql.Date

            // Gọi DAO để lấy danh sách ca
            Ca_DAO dao = new Ca_DAO();
            List<Ca> danhSachCa = dao.getByNgay(ngay_1);

            // Hiển thị lên bảng
            DefaultTableModel model = (DefaultTableModel) table_ca.getModel();
            model.setRowCount(0); // Xóa dữ liệu cũ

            for (Ca ca : danhSachCa) {
                model.addRow(new Object[]{
                    ca.getMaCa(),
                    ca.getNgay(),
                    ca.getTimeStart(),
                    ca.getTimeEnd(),
                    ca.getLuongCa(),
                    ca.getSoluongCa(),
                    ca.getSoluongDky()
                });
            }

            if (danhSachCa.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không có ca nào trong ngày " + ngayStr);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_but_tim_ngayActionPerformed

    private void but_dangkycalamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_dangkycalamActionPerformed
        // TODO add your handling code here:
          try {
        String maCa = txt_maca.getText();
        String maNhanVien = Form_login.MaNV; // Mã NV hiện tại (đã đăng nhập)
        String ngay = txt_ngay.getText(); // Định dạng yyyy-MM-dd
        String gioBatDau = txt_giobatdau.getText();
        String gioKetThuc = txt_gioketthuc.getText();
        double luong = Double.parseDouble(txt_luong.getText());

            Ca_DAO cadao= new Ca_DAO();

            Ca ca = cadao.selectById(maCa);
            if (ca.getSoluongDky()<ca.getSoluongCa()){
            int k =ca.getSoluongDky()+1;
            ca.setSoluongDky(k);
            
            cadao.update(ca);
            JOptionPane.showMessageDialog(this, "Đăng ký ca làm thành công");
            
        // Tạo mã phân lịch (ví dụ: 20250604_1)
        String maPhanLich = maCa + "_" +maNhanVien;

        LichLamViec lich = new LichLamViec();
        lich.setMaPhanLich(maPhanLich);
        lich.setMaNhanVien(maNhanVien);
        lich.setNgay(Date.valueOf(ngay));
        lich.setCa(maCa);
        lich.setLuong(luong);
        lich.setTrangThai(1); // 1: Đã đăng ký

        LichLamViec_DAO dao = new LichLamViec_DAO();
        if (dao.insert(lich)) {
            JOptionPane.showMessageDialog(this, "Đăng ký ca làm thành công");
            loadTable();
            hienThiNhanVienTrongCa(maCa);
        fillTableDoiCa();
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi.");
        }
            } else JOptionPane.showMessageDialog(this, "Lỗi.");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi. " );
    }
    }//GEN-LAST:event_but_dangkycalamActionPerformed

    private void but_dongydoicadoicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_dongydoicadoicaActionPerformed
       try {
    String ma_doi = Label_madoica.getText();
    DoiCa_DAO doica_dao = new DoiCa_DAO();
    DoiCa doica = doica_dao.selectById(ma_doi);

    if (doica.getTrangThai() == 0) {
        LichLamViec_DAO lich_dao = new LichLamViec_DAO();

        // Lấy mã lịch làm việc từ phiếu đổi ca
        String maLich1 = doica.getMaPhanLich1();
        String maLich2 = doica.getMaPhanLich2();

        // Lấy 2 lịch làm việc
        LichLamViec lichlam1 = lich_dao.getById(maLich1);
        LichLamViec lichlam2 = lich_dao.getById(maLich2);

        // Kiểm tra null trước khi dùng
        if (lichlam1 == null || lichlam2 == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy một trong hai lịch làm việc.");
            return;
        }

        // Hoán đổi nhân viên
        String nv1 = lichlam1.getMaNhanVien();
        String nv2 = lichlam2.getMaNhanVien();

        lichlam1.setMaNhanVien(nv2);
        lichlam2.setMaNhanVien(nv1);

        // Cập nhật lại lịch
        lich_dao.update(lichlam1);
        lich_dao.update(lichlam2);

        // Đánh dấu đã duyệt
        doica.setTrangThai(1);
        doica_dao.update(doica);

        // Refresh bảng
        loadTable();
        fillTableDoiCa();

        JOptionPane.showMessageDialog(this, "Duyệt đổi ca thành công.");

    } else {
        JOptionPane.showMessageDialog(this, "Yêu cầu đã được duyệt trước đó.");
    }
} catch (SQLException ex) {
    ex.printStackTrace(); // In lỗi ra console giúp debug
    JOptionPane.showMessageDialog(this, "Lỗi khi duyệt đổi ca.");
}

        
    }//GEN-LAST:event_but_dongydoicadoicaActionPerformed

    private void but_tuchoidoicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_tuchoidoicaActionPerformed
        // TODO add your handling code here:
        String madoi = Label_madoica.getText();
        DoiCa_DAO doi_DAO = new DoiCa_DAO();
        try {
            DoiCa doica = doi_DAO.selectById(madoi);
            if ( doica.getTrangThai()==0){
            doica.setTrangThai(2);
            doi_DAO.update(doica);
            fillTableDoiCa();}
            else {
                JOptionPane.showMessageDialog(this, "Đã duyệt."); 
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "Lỗi.");
        }
    }//GEN-LAST:event_but_tuchoidoicaActionPerformed

    private void table_doicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_doicaMouseClicked
        // TODO add your handling code here:int row = table_doica.getSelectedRow();
        int row = table_doica.getSelectedRow();
    if (row != -1) {
        Label_madoica.setText(table_doica.getValueAt(row, 0).toString());
        Label_lich1.setText(table_doica.getValueAt(row, 1).toString());
        Label_lich2.setText(table_doica.getValueAt(row, 2).toString());
        Label_nhanvien1.setText(table_doica.getValueAt(row, 3).toString());
        Label_nhanvien2.setText(table_doica.getValueAt(row, 4).toString());
        
       
    }
    }//GEN-LAST:event_table_doicaMouseClicked

    private void table_lamviecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_lamviecMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_lamviec.getSelectedRow();
        if (selectedRow != -1) {
            String maPhanLich = table_lamviec.getValueAt(selectedRow, 0).toString();
            String nv1 = table_lamviec.getValueAt(selectedRow, 1).toString();// Mã phân lịch
            // Trạng thái (Làm/Nghỉ)

            txt_lich1.setText(maPhanLich);
            Label_nv1.setText(nv1);
            
        }
    }//GEN-LAST:event_table_lamviecMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
    String nv1 = Label_nv1.getText();
    String nv2 = Form_login.MaNV;
    String lich1 = txt_lich1.getText();  
    String lich2 = txt_lich2.getText();
    String madoi = nv1 + "_" + nv2 + "_" + lich1 + "_" + lich2;

    DoiCa doica = new DoiCa(madoi, lich1, lich2, nv1, nv2 ,0);
    DoiCa_DAO doi_DAO = new DoiCa_DAO();
    
    boolean success = doi_DAO.insert(doica);
    if (success) {
        JOptionPane.showMessageDialog(this, "Gửi yêu cầu đổi ca thành công.");
        // load lại bảng đổi ca nếu cần
        loadTable();
        fillTableDoiCa();
    } else {
        JOptionPane.showMessageDialog(this, "Thêm đổi ca thất bại.");
        loadTable();
        fillTableDoiCa();
        hienThiNhanVienTrongCa(madoi);
    }
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Lỗi khi gửi yêu cầu đổi ca " );
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        if (Form_login.role==1) {
                    // Admin login
                     
                    Form_Ca nv = new Form_Ca();
                    nv.setVisible(true);
                    this.dispose();
                } else {
                    // Nhân viên login
              
                    Form_MainNV nv = new Form_MainNV();
                    nv.setVisible(true);
                    this.dispose();
                }
    }//GEN-LAST:event_but_backActionPerformed

    private void but_xoacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoacaActionPerformed
        // TODO add your handling code here:
        try {
    String nv1 = Label_nv1.getText();
    String nv2 = Form_login.MaNV;
    String lich1 = txt_lich1.getText();  

    LichLamViec_DAO lich_dao = new LichLamViec_DAO();
    LichLamViec lich = lich_dao.getById(lich1);

    if (nv1.equals(nv2)) {
        String ca_1 = lich.getCa();

        // Xóa phân lịch
        lich_dao.delete(lich1);

        // Cập nhật lại số lượng đăng ký ca
        Ca_DAO ca_dao = new Ca_DAO();
        Ca ca = ca_dao.selectById(ca_1);
        int r = ca.getSoluongDky() - 1;
        ca.setSoluongDky(r);
        ca_dao.update(ca);

        // Xóa đổi ca nếu có liên quan đến phân lịch vừa xóa và trạng thái đang chờ
        DoiCa_DAO doica_dao = new DoiCa_DAO();
        doica_dao.deleteIfWaitingByPhanLich(lich1);

        fillTableDoiCa();
        loadTable();
        JOptionPane.showMessageDialog(this, "Xoá thành công.");
    } else {
        JOptionPane.showMessageDialog(this, "Đây không phải ca làm của bạn.");
    }
} catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(this, "Lỗi khi xoá ca.");
}

    }//GEN-LAST:event_but_xoacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Dangkylamviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Dangkylamviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Dangkylamviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Dangkylamviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Dangkylamviec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_ngay;
    private javax.swing.JLabel Label_lich1;
    private javax.swing.JLabel Label_lich2;
    private javax.swing.JLabel Label_madoica;
    private javax.swing.JLabel Label_nhanvien1;
    private javax.swing.JLabel Label_nhanvien2;
    private javax.swing.JLabel Label_nv1;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_dangkycalam;
    private javax.swing.JButton but_dongydoica;
    private javax.swing.JButton but_tim_ngay;
    private javax.swing.JButton but_tuchoidoica;
    private javax.swing.JButton but_xoaca;
    private javax.swing.JComboBox<String> combobox_nam;
    private javax.swing.JComboBox<String> combobox_thang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_ca;
    private javax.swing.JTable table_doica;
    private javax.swing.JTable table_lamviec;
    private javax.swing.JTextField txt_giobatdau;
    private javax.swing.JTextField txt_gioketthuc;
    private javax.swing.JTextField txt_lich1;
    private javax.swing.JTextField txt_lich2;
    private javax.swing.JTextField txt_luong;
    private javax.swing.JTextField txt_maca;
    private javax.swing.JTextField txt_ngay;
    private javax.swing.JTextField txt_sonhanvien;
    // End of variables declaration//GEN-END:variables
}
