/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.CheBien_DAO;
import DAO.Mon_DAO;
import DAO.Nguyenlieu_DAO;
import Lop.CheBien;
import Lop.Mon;
import Lop.Nguyenlieu;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_Make extends javax.swing.JFrame {

    /**
     * Creates new form Form_Make
     */
    public Form_Make() {
        initComponents();
        loadCheBienTable();
        loadTable_Mon();
        loadTable_NguyenLieu();
    }
    private void loadTable_Mon() {
    DefaultTableModel model = (DefaultTableModel) table_mamon.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ
    Mon_DAO dao = new Mon_DAO();
    List<Mon> dsMon = dao.selectAll();
    for (Mon m : dsMon) {
        model.addRow(new Object[]{m.getMa_Mon(), m.getTen_Mon(),m.getGia_Mon()});
    }
}
    private void loadCheBienTable() {
    CheBien_DAO dao= new CheBien_DAO();
    List<CheBien> ds = dao.selectAll();
    DefaultTableModel model = (DefaultTableModel) table_chebien.getModel();
    model.setRowCount(0);
    for (CheBien cb : ds) {
        model.addRow(new Object[]{cb.getMa_Mon(), cb.getMa_Nglieu(), cb.getSL_chebien()});
    }
}
    private void loadTable_NguyenLieu() {
    DefaultTableModel model = (DefaultTableModel) table_nguyenlieu.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ
    Nguyenlieu_DAO dao= new Nguyenlieu_DAO();
    List<Nguyenlieu> dsNL = dao.selectAll();
    for (Nguyenlieu nl : dsNL) {
        model.addRow(new Object[]{nl.getMa_Nglieu(), nl.getTen_Nglieu(),nl.getSL_NL()});
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        but_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_mamonchebien = new javax.swing.JTextField();
        but_search_mamonchebien = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_chebien = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_manguyenlieuchebien = new javax.swing.JTextField();
        but_xoa_chebien = new javax.swing.JButton();
        but_capnhat_chebien = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_mamon_chebien = new javax.swing.JTextField();
        but_them_chebien = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_soluong_chebien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_search_mamonchebien = new javax.swing.JTextField();
        but_timmamonchebien = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_search_manglieu = new javax.swing.JTextField();
        but_search_manglieu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_nguyenlieu = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_mamon = new javax.swing.JTable();
        txt_search_mamon = new javax.swing.JTextField();
        but_search_mon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        but_back.setBackground(new java.awt.Color(102, 255, 255));
        but_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_back.setText("Back");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Chế biến");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_back, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_back)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã chế biến :");

        but_search_mamonchebien.setBackground(new java.awt.Color(204, 255, 204));
        but_search_mamonchebien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_search_mamonchebien.setText("Tìm");
        but_search_mamonchebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_search_mamonchebienActionPerformed(evt);
            }
        });

        table_chebien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã món", "Mã nguyên liệu", "Số lượng"
            }
        ));
        table_chebien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_chebienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_chebien);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã nguyên liệu :");

        txt_manguyenlieuchebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_manguyenlieuchebienActionPerformed(evt);
            }
        });

        but_xoa_chebien.setBackground(new java.awt.Color(255, 255, 204));
        but_xoa_chebien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_xoa_chebien.setText("Xoá");
        but_xoa_chebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoa_chebienActionPerformed(evt);
            }
        });

        but_capnhat_chebien.setBackground(new java.awt.Color(255, 255, 204));
        but_capnhat_chebien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_capnhat_chebien.setText("Cập nhật");
        but_capnhat_chebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhat_chebienActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Mã món :");

        but_them_chebien.setBackground(new java.awt.Color(255, 255, 204));
        but_them_chebien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_them_chebien.setText("Thêm");
        but_them_chebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_them_chebienActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Số lượng :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Mã món :");

        but_timmamonchebien.setBackground(new java.awt.Color(204, 255, 204));
        but_timmamonchebien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_timmamonchebien.setText("Tìm");
        but_timmamonchebien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timmamonchebienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addComponent(but_capnhat_chebien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_soluong_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(246, 246, 246))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but_them_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_xoa_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_mamon_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_manguyenlieuchebien, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(68, 68, 68))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_search_mamonchebien, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_mamonchebien, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_search_mamonchebien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but_timmamonchebien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mamonchebien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_search_mamonchebien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_search_mamonchebien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_timmamonchebien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mamon_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_manguyenlieuchebien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soluong_chebien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_xoa_chebien)
                    .addComponent(but_them_chebien)
                    .addComponent(but_capnhat_chebien))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã nguyên liệu :");

        but_search_manglieu.setBackground(new java.awt.Color(204, 255, 204));
        but_search_manglieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_search_manglieu.setText("Tìm");
        but_search_manglieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_search_manglieuActionPerformed(evt);
            }
        });

        table_nguyenlieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã nguyên liệu", "Tên nguyên liệu", "Số lượng tồn kho"
            }
        ));
        jScrollPane3.setViewportView(table_nguyenlieu);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã món :");

        table_mamon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Giá"
            }
        ));
        jScrollPane4.setViewportView(table_mamon);

        but_search_mon.setBackground(new java.awt.Color(204, 255, 204));
        but_search_mon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_search_mon.setText("Tìm");
        but_search_mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_search_monActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_search_manglieu, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_search_manglieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(txt_search_mamon, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(but_search_mon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_search_manglieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_search_manglieu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search_mamon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(but_search_mon))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_xoa_chebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoa_chebienActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_chebien.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa!");
        return;
    }

    String maMon = table_chebien.getValueAt(selectedRow, 0).toString();
    String maNguyenLieu = table_chebien.getValueAt(selectedRow, 1).toString();

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Bạn có chắc chắn muốn xóa nguyên liệu này khỏi món?", "Xác nhận", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            CheBien_DAO dao =new CheBien_DAO();
            dao.delete(maMon, maNguyenLieu);
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
            loadCheBienTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_but_xoa_chebienActionPerformed

    private void but_capnhat_chebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhat_chebienActionPerformed
        // TODO add your handling code here:
        String maMon = txt_mamonchebien.getText().trim();
    String maNguyenLieu = txt_manguyenlieuchebien.getText().trim();
    String soLuongStr = txt_soluong_chebien.getText().trim();

    if (maMon.isEmpty() || maNguyenLieu.isEmpty() || soLuongStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }

    try {
        int soLuong = Integer.parseInt(soLuongStr);
        CheBien cb = new CheBien(maMon, maNguyenLieu, soLuong);
        CheBien_DAO dao =new CheBien_DAO();
        dao.update(cb);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        loadCheBienTable();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_but_capnhat_chebienActionPerformed

    private void but_them_chebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_them_chebienActionPerformed
        // TODO add your handling code here:
    String maMon = txt_mamon_chebien.getText().trim();
    String maNguyenLieu = txt_manguyenlieuchebien.getText().trim();
    String soLuongStr = txt_soluong_chebien.getText().trim();

    if (maMon.isEmpty() ||maNguyenLieu.isEmpty() ||  soLuongStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }

    try {
        int soLuong = Integer.parseInt(soLuongStr);
        CheBien cb = new CheBien(maMon, maNguyenLieu, soLuong);
        CheBien_DAO dao =new CheBien_DAO();
        dao.insert(cb);
        JOptionPane.showMessageDialog(this, "Thêm nguyên liệu vào món thành công!");
        loadCheBienTable(); // làm mới bảng hiển thị
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_but_them_chebienActionPerformed

    private void but_search_mamonchebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_mamonchebienActionPerformed
        // TODO add your handling code here:
        String keyword = txt_mamonchebien.getText().trim();
         if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa để tìm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
         CheBien_DAO dao =new CheBien_DAO();
    List<CheBien> dsCB = dao.selectByMaMon(keyword);
    DefaultTableModel model = (DefaultTableModel) table_chebien.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ
    
    for (CheBien cb : dsCB) {
        model.addRow(new Object[]{
            cb.getMa_Mon(),
            cb.getMa_Nglieu(),
            cb.getMa_Nglieu()
        });
    }
    }//GEN-LAST:event_but_search_mamonchebienActionPerformed

    private void but_search_manglieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_manglieuActionPerformed
        // TODO add your handling code here:
    String keyword = txt_search_manglieu.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa để tìm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Nguyenlieu_DAO dao = new Nguyenlieu_DAO();
        Nguyenlieu nl = dao.selectById(keyword);
        DefaultTableModel model = (DefaultTableModel) table_nguyenlieu.getModel();
        model.setRowCount(0);
        if (nl != null) {
            model.addRow(new Object[]{
                nl.getMa_Nglieu(), nl.getTen_Nglieu(), nl.getSL_NL(), nl.getGia_Nglieu(), nl.getSL_NLin(), nl.getDate_Nglieu()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nguyên liệu!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_but_search_manglieuActionPerformed

    private void but_search_monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_monActionPerformed
        // TODO add your handling code here:
        String maMon = txt_search_mamon.getText().trim();
    if (maMon.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã món để tìm!");
        return;
    }

    Mon_DAO dao = new Mon_DAO();
    Mon mon = dao.selectByMa_Mon(maMon);

    DefaultTableModel model = (DefaultTableModel) table_mamon.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    if (mon != null) {
        model.addRow(new Object[]{
            mon.getMa_Mon(),
            mon.getTen_Mon(),
            mon.getGia_Mon(),
            mon.getMa_LM(),
            mon.getHinhanh()
        });
    } else {
        JOptionPane.showMessageDialog(this, "Không tìm thấy món!");
    }
    }//GEN-LAST:event_but_search_monActionPerformed

    private void table_chebienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_chebienMouseClicked
        // TODO add your handling code here:
        int row = table_chebien.getSelectedRow();
    if (row >= 0) {
        String mamon = table_chebien.getValueAt(row, 0).toString();
        String mangl = table_chebien.getValueAt(row, 1).toString();
        String soluong = table_chebien.getValueAt(row, 2).toString();

        txt_mamon_chebien.setText(mamon);
        txt_manguyenlieuchebien.setText(mangl);
        txt_soluong_chebien.setText(soluong);
    }
    }//GEN-LAST:event_table_chebienMouseClicked

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:\
        Form_Main nv = new Form_Main();
                    nv.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_but_backActionPerformed

    private void txt_manguyenlieuchebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_manguyenlieuchebienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_manguyenlieuchebienActionPerformed

    private void but_timmamonchebienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timmamonchebienActionPerformed
        // TODO add your handling code here:
        String keyword = txt_search_mamonchebien.getText().trim();
         if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa để tìm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
         CheBien_DAO dao =new CheBien_DAO();
    List<CheBien> dsCB = dao.selectByMaMon(keyword);
    DefaultTableModel model = (DefaultTableModel) table_chebien.getModel();
    model.setRowCount(0); // Xoá dữ liệu cũ
    
    for (CheBien cb : dsCB) {
        model.addRow(new Object[]{
            cb.getMa_Mon(),
            cb.getMa_Nglieu(),
            cb.getMa_Nglieu()
        });
    }
        
    }//GEN-LAST:event_but_timmamonchebienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Make.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Make().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_capnhat_chebien;
    private javax.swing.JButton but_search_mamonchebien;
    private javax.swing.JButton but_search_manglieu;
    private javax.swing.JButton but_search_mon;
    private javax.swing.JButton but_them_chebien;
    private javax.swing.JButton but_timmamonchebien;
    private javax.swing.JButton but_xoa_chebien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable table_chebien;
    private javax.swing.JTable table_mamon;
    private javax.swing.JTable table_nguyenlieu;
    private javax.swing.JTextField txt_mamon_chebien;
    private javax.swing.JTextField txt_mamonchebien;
    private javax.swing.JTextField txt_manguyenlieuchebien;
    private javax.swing.JTextField txt_search_mamon;
    private javax.swing.JTextField txt_search_mamonchebien;
    private javax.swing.JTextField txt_search_manglieu;
    private javax.swing.JTextField txt_soluong_chebien;
    // End of variables declaration//GEN-END:variables
}
