/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import DAO.Ca_DAO;
import DAO.LichLamViec_DAO;
import Lop.Ca;
import Lop.LichLamViec;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADM
 */
public class Form_Ca extends javax.swing.JFrame {

    /**
     * Creates new form Form_Ca
     */
    public Form_Ca() {
        initComponents();
        loadTable();
    }
    private void loadTable() {
    try {
        
        Ca_DAO ca_DAO= new Ca_DAO();
        
        List<Ca> list = ca_DAO.selectAll();
        DefaultTableModel model = (DefaultTableModel) table_ca.getModel();
        model.setRowCount(0);
        for (Ca ca : list) {
            model.addRow(new Object[]{
                ca.getMaCa(),
                ca.getNgay().toString(),
                ca.getTimeStart(),
                ca.getTimeEnd(),
                ca.getLuongCa(),
                ca.getSoluongCa(),
                ca.getSoluongDky()
            });
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
   private void hienThiNhanVienTrongCa(String maCa) {
    try {
        LichLamViec_DAO dao = new LichLamViec_DAO();
        List<LichLamViec> danhSach = dao.getByCa(maCa);

        DefaultTableModel model = (DefaultTableModel) table_lamviec.getModel();
        model.setRowCount(0); // Xoá dữ liệu cũ

        for (LichLamViec lich : danhSach) {
            model.addRow(new Object[]{
                lich.getMaPhanLich(),
                lich.getMaNhanVien(),               
                lich.getCa(),
                lich.getNgay(),
                lich.getTrangThai() == 1 ? "Làm" : "Nghỉ"
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi hiển thị nhân viên làm việc trong ca: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ca = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Combobox_ngay = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combobox_thang = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        combobox_nam = new javax.swing.JComboBox<>();
        but_tim_ngay = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_maca = new javax.swing.JTextField();
        txt_ngay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_giobatdau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_gioketthuc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_luong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sonhanvien = new javax.swing.JTextField();
        but_them = new javax.swing.JButton();
        but_capnhar = new javax.swing.JButton();
        but_xoa = new javax.swing.JButton();
        but_themtudongtheongay = new javax.swing.JButton();
        them_tudongtheotuan = new javax.swing.JButton();
        but_timtatca = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_lamviec = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Label_Maphanlich = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBox_trangthai = new javax.swing.JComboBox<>();
        but_updatelamviec = new javax.swing.JButton();
        label_maphanlich = new javax.swing.JLabel();
        but_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Quản lý lịch làm việc");

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        table_ca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ca", "Ngày", "Giờ bắt đầu", "Giờ kết thúc", "Lương", "Số nhân viên", "Đăng ký"
            }
        ));
        table_ca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_caMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ca);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngày :");

        Combobox_ngay.setMaximumRowCount(32);
        Combobox_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tháng :");

        combobox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Năm :");

        combobox_nam.setModel(new javax.swing.DefaultComboBoxModel<String>(
            java.util.stream.IntStream.rangeClosed(2000, java.time.Year.now().getValue())
            .mapToObj(String::valueOf)
            .toArray(String[]::new)
        )

    );
    combobox_nam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            combobox_namActionPerformed(evt);
        }
    });

    but_tim_ngay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_tim_ngay.setText("Tìm");
    but_tim_ngay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_tim_ngayActionPerformed(evt);
        }
    });

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel5.setText("Mã ca :");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel6.setText("Ngày :");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel7.setText("Bắt đầu :");

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel8.setText("Kết thúc :");

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel9.setText("Lương :");

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel10.setText("Số người :");

    but_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_them.setText("Thêm");
    but_them.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_themActionPerformed(evt);
        }
    });

    but_capnhar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_capnhar.setText("Cập nhật");
    but_capnhar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_capnharActionPerformed(evt);
        }
    });

    but_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_xoa.setText("Xoá");
    but_xoa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_xoaActionPerformed(evt);
        }
    });

    but_themtudongtheongay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_themtudongtheongay.setText("Thêm tự động ngày");
    but_themtudongtheongay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_themtudongtheongayActionPerformed(evt);
        }
    });

    them_tudongtheotuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    them_tudongtheotuan.setText("Thêm tự động tuần");
    them_tudongtheotuan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            them_tudongtheotuanActionPerformed(evt);
        }
    });

    but_timtatca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_timtatca.setText("Tìm tất cả");
    but_timtatca.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_timtatcaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane1)
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(Combobox_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(but_tim_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(but_timtatca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(txt_maca))
                    .addGap(39, 39, 39)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_giobatdau)
                        .addComponent(txt_gioketthuc, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_luong)
                        .addComponent(txt_sonhanvien))
                    .addContainerGap())
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(but_themtudongtheongay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(86, 86, 86)
                            .addComponent(them_tudongtheotuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(but_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(72, 72, 72)
                            .addComponent(but_capnhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(103, 103, 103)
                            .addComponent(but_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGap(68, 68, 68))))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Combobox_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addComponent(but_tim_ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_timtatca))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(txt_maca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel7)
                .addComponent(txt_giobatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9)
                .addComponent(txt_luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(txt_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(txt_gioketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10)
                .addComponent(txt_sonhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(but_them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_capnhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(31, 31, 31)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(but_themtudongtheongay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(them_tudongtheotuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(77, 77, 77))
    );

    table_lamviec.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null},
            {null, null, null, null, null}
        },
        new String [] {
            "Mã phân lịch", "Mã nhân viên", "Mã ca", "Ngày", "Trạng thái"
        }
    ));
    table_lamviec.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_lamviecMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(table_lamviec);

    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jButton1.setText("Đăng ký lịch làm việc");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel11.setText("Mã phân lịch :");

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel12.setText("Trạng thái :");

    comboBox_trangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Làm", "Nghỉ" }));

    but_updatelamviec.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    but_updatelamviec.setText("Cập nhật");
    but_updatelamviec.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_updatelamviecActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Label_Maphanlich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label_maphanlich, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                            .addGap(11, 11, 11)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(comboBox_trangthai, 0, 107, Short.MAX_VALUE))
                        .addComponent(but_updatelamviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
            .addGap(10, 10, 10))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(Label_Maphanlich)
                .addComponent(jLabel12)
                .addComponent(comboBox_trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(label_maphanlich))
            .addGap(27, 27, 27)
            .addComponent(but_updatelamviec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
            .addGap(11, 11, 11))
    );

    but_back.setBackground(new java.awt.Color(102, 255, 255));
    but_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    but_back.setText("Back");
    but_back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_backActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(but_back)
            .addGap(377, 377, 377)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addGap(237, 237, 237))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addComponent(but_back))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combobox_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_namActionPerformed

    private void but_capnharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnharActionPerformed
        // TODO add your handling code here:
                                                  
    try {
        String maCa = txt_maca.getText();
        String ngayStr = txt_ngay.getText(); // yyyy-MM-dd
        Date ngay = Date.valueOf(ngayStr);
        Timestamp timeStart = Timestamp.valueOf(ngayStr + " " + txt_giobatdau.getText() + ":00");
        Timestamp timeEnd = Timestamp.valueOf(ngayStr + " " + txt_gioketthuc.getText() + ":00");
        double luong = Double.parseDouble(txt_luong.getText());
        int soLuong = Integer.parseInt(txt_sonhanvien.getText());

        Ca ca_1= new Ca() ;
        ca_1.setMaCa(maCa);
        ca_1.setNgay(ngay);
        ca_1.setTimeStart(timeStart);
        ca_1.setTimeEnd(timeEnd);
        ca_1.setLuongCa(luong);
        ca_1.setSoluongCa(soLuong);
        Ca_DAO dao = new Ca_DAO();

        boolean updated = dao.update(ca_1);
        if (updated) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy mã ca để cập nhật.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_but_capnharActionPerformed

    private void but_themtudongtheongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themtudongtheongayActionPerformed
        // TODO add your handling code here:
         try {
        // Lấy ngày hiện tại hệ thống (LocalDate)
        java.time.LocalDate today = java.time.LocalDate.now();

        // Chuyển LocalDate sang String yyyy-MM-dd
        String ngayStr = today.toString();

        // Chuyển LocalDate sang java.sql.Date
        java.sql.Date ngay = java.sql.Date.valueOf(today);

        // Danh sách các mốc thời gian cho 3 ca
        String[] batDau = {"06:00:00", "12:00:00", "18:00:00"};
        String[] ketThuc = {"12:00:00", "18:00:00", "23:59:59"};

        Ca_DAO caDAO = new Ca_DAO(); // Tạo đối tượng DAO 1 lần ngoài vòng for

        for (int i = 0; i < 3; i++) {
            String maCa = ngayStr.replace("-", "") + "_ca" + (i + 1);

            Timestamp timeStart = Timestamp.valueOf(ngayStr + " " + batDau[i]);
            Timestamp timeEnd = Timestamp.valueOf(ngayStr + " " + ketThuc[i]);

            Ca ca = new Ca();
            ca.setMaCa(maCa);
            ca.setNgay(ngay);
            ca.setTimeStart(timeStart);
            ca.setTimeEnd(timeEnd);
            ca.setLuongCa(120000); 
            ca.setSoluongCa(2);// hoặc set theo input nếu có

            caDAO.insert(ca);
        }

        JOptionPane.showMessageDialog(this, "Thêm 3 ca cho ngày " + ngayStr + " thành công!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm ca: " + e.getMessage());
    }
    }//GEN-LAST:event_but_themtudongtheongayActionPerformed

    private void but_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_themActionPerformed
        try {
        Ca ca = new Ca();
        ca.setMaCa(txt_maca.getText());
        ca.setNgay(Date.valueOf(txt_ngay.getText())); // Format: yyyy-MM-dd

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        ca.setTimeStart(new java.util.Date(sdf.parse(txt_ngay.getText() + " " + txt_giobatdau.getText()).getTime()));
        ca.setTimeEnd(new java.util.Date(sdf.parse(txt_ngay.getText() + " " + txt_gioketthuc.getText()).getTime()));

        ca.setLuongCa(Double.parseDouble(txt_luong.getText()));
        ca.setSoluongCa(Integer.parseInt(txt_sonhanvien.getText()));
        ca.setSoluongDky(0); // Mặc định 0
        Ca_DAO ca_DAO= new Ca_DAO();
        ca_DAO.insert(ca);
        JOptionPane.showMessageDialog(this, "Thêm thành công!");
        loadTable();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm ca!");
    }
    }//GEN-LAST:event_but_themActionPerformed

    private void but_tim_ngayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_tim_ngayActionPerformed
        // TODO add your handling code here:
        try {
    // Lấy dữ liệu từ ComboBox thay vì TextField
    String nam = combobox_nam.getSelectedItem().toString();
    String thang = combobox_thang.getSelectedItem().toString();
    String ngay = Combobox_ngay.getSelectedItem().toString();

    // Đảm bảo đúng định dạng yyyy-MM-dd
    String ngayStr = nam + "-" + thang + "-" + ngay;
    Date ngay_1 = Date.valueOf(ngayStr); // java.sql.Date

    // Gọi DAO để lấy danh sách ca
    Ca_DAO dao = new Ca_DAO();
    List<Ca> danhSachCa = dao.getByNgay(ngay_1);

    // Hiển thị lên bảng
    DefaultTableModel model = (DefaultTableModel) table_ca.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    for (Ca ca : danhSachCa) {
        model.addRow(new Object[]{
            ca.getMaCa(),
            ca.getNgay(),
            ca.getTimeStart(),
            ca.getTimeEnd(),
            ca.getLuongCa(),
            ca.getSoluongCa(),
            ca.getSoluongDky()
        });
    }

    if (danhSachCa.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không có ca nào trong ngày " + ngayStr);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    e.printStackTrace();
}

    }//GEN-LAST:event_but_tim_ngayActionPerformed

    private void but_timtatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timtatcaActionPerformed
        // TODO add your handling code here:
                                               
    try {
        Ca_DAO dao = new Ca_DAO();
        List<Ca> danhSachCa = dao.selectAll();

        DefaultTableModel model = (DefaultTableModel) table_ca.getModel();
        model.setRowCount(0); // Clear table

        for (Ca ca : danhSachCa) {
            model.addRow(new Object[]{
                ca.getMaCa(), ca.getNgay(), ca.getTimeStart(), ca.getTimeEnd(),
                ca.getLuongCa(), ca.getSoluongCa(), ca.getSoluongDky()
            });
        }

        if (danhSachCa.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có ca nào.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        e.printStackTrace();
    }

    }//GEN-LAST:event_but_timtatcaActionPerformed

    private void but_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoaActionPerformed
        // TODO add your handling code here:
         int row = table_ca.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng để xóa");
        return;
    }
    String maCa = table_ca.getValueAt(row, 0).toString();
    try {
        Ca_DAO caDAO = new Ca_DAO();
        caDAO.delete(maCa);
        loadTable();
        JOptionPane.showMessageDialog(this, "Xóa thành công!");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Xóa thất bại!");
    }
    }//GEN-LAST:event_but_xoaActionPerformed

    private void them_tudongtheotuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_them_tudongtheotuanActionPerformed
        // TODO add your handling code here:
        try {
    LocalDate ngayBatDau = LocalDate.now();  // Lấy ngày hiện tại hệ thống
    String ngayStr = ngayBatDau.toString();  // Chuyển sang chuỗi yyyy-MM-dd
    Ca_DAO caDAO = new Ca_DAO();

    String[] batDau = {"06:00:00", "12:00:00", "18:00:00"};
    String[] ketThuc = {"12:00:00", "18:00:00", "23:59:59"};

    for (int d = 0; d < 7; d++) {
        LocalDate ngayHienTai = ngayBatDau.plusDays(d);
        String ngayStrHienTai = ngayHienTai.toString();

        for (int i = 0; i < 3; i++) {
            String maCa = ngayStrHienTai.replace("-", "") + "_ca" + (i + 1);
            Timestamp timeStart = Timestamp.valueOf(ngayStrHienTai + " " + batDau[i]);
            Timestamp timeEnd = Timestamp.valueOf(ngayStrHienTai + " " + ketThuc[i]);

            Ca ca = new Ca();
            ca.setMaCa(maCa);
            ca.setNgay(Date.valueOf(ngayHienTai));
            ca.setTimeStart(timeStart);
            ca.setTimeEnd(timeEnd);
            ca.setLuongCa(120000);
            ca.setSoluongCa(2);

            caDAO.insert(ca);
        }
    }

    JOptionPane.showMessageDialog(this, "Đã thêm 3 ca mỗi ngày cho 7 ngày từ " + ngayStr);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
    e.printStackTrace();
}
    }//GEN-LAST:event_them_tudongtheotuanActionPerformed

    private void table_caMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_caMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_ca.getSelectedRow();
    if (selectedRow != -1) {
        String maCa = table_ca.getValueAt(selectedRow, 0).toString(); // Cột 0 là mã ca
        hienThiNhanVienTrongCa(maCa);
        txt_maca.setText(table_ca.getValueAt(selectedRow, 0).toString());
            txt_ngay.setText(table_ca.getValueAt(selectedRow, 1).toString());
            txt_giobatdau.setText(table_ca.getValueAt(selectedRow, 2).toString());
            txt_gioketthuc.setText(table_ca.getValueAt(selectedRow, 3).toString());
            txt_luong.setText(table_ca.getValueAt(selectedRow, 4).toString());
            txt_sonhanvien.setText(table_ca.getValueAt(selectedRow, 5).toString());
    }
    }//GEN-LAST:event_table_caMouseClicked

    private void table_lamviecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_lamviecMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_lamviec.getSelectedRow();
    if (selectedRow != -1) {
        String maPhanLich = table_lamviec.getValueAt(selectedRow, 0).toString(); // Mã phân lịch
        String trangThaiText = table_lamviec.getValueAt(selectedRow, 5).toString(); // Trạng thái (Làm/Nghỉ)

        label_maphanlich.setText(maPhanLich);
        comboBox_trangthai.setSelectedItem(trangThaiText); // "Làm" hoặc "Nghỉ"
    }
    }//GEN-LAST:event_table_lamviecMouseClicked

    private void but_updatelamviecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_updatelamviecActionPerformed
        // TODO add your handling code here:
         try {
        String maPhanLich = label_maphanlich.getText();
        String trangThaiStr = comboBox_trangthai.getSelectedItem().toString();

        if (maPhanLich.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng lịch làm việc.");
            return;
        }

        int trangThai = trangThaiStr.equals("Làm") ? 1 : 0;

        // Lấy bản ghi hiện tại
        LichLamViec_DAO dao = new LichLamViec_DAO();
        LichLamViec lich = dao.getById(maPhanLich);
        if (lich != null) {
            lich.setTrangThai(trangThai);
            if (dao.update(lich)) {
                JOptionPane.showMessageDialog(this, "Cập nhật trạng thái thành công.");
                hienThiNhanVienTrongCa(lich.getCa()); // refresh lại table
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bại.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy phân lịch.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật trạng thái: " + e.getMessage());
    }
    }//GEN-LAST:event_but_updatelamviecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Form_Dangkylamviec nv = new Form_Dangkylamviec();
                    nv.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:
        Form_Main nv = new Form_Main();
                    nv.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_but_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Ca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Ca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combobox_ngay;
    private javax.swing.JLabel Label_Maphanlich;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_capnhar;
    private javax.swing.JButton but_them;
    private javax.swing.JButton but_themtudongtheongay;
    private javax.swing.JButton but_tim_ngay;
    private javax.swing.JButton but_timtatca;
    private javax.swing.JButton but_updatelamviec;
    private javax.swing.JButton but_xoa;
    private javax.swing.JComboBox<String> comboBox_trangthai;
    private javax.swing.JComboBox<String> combobox_nam;
    private javax.swing.JComboBox<String> combobox_thang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_maphanlich;
    private javax.swing.JTable table_ca;
    private javax.swing.JTable table_lamviec;
    private javax.swing.JButton them_tudongtheotuan;
    private javax.swing.JTextField txt_giobatdau;
    private javax.swing.JTextField txt_gioketthuc;
    private javax.swing.JTextField txt_luong;
    private javax.swing.JTextField txt_maca;
    private javax.swing.JTextField txt_ngay;
    private javax.swing.JTextField txt_sonhanvien;
    // End of variables declaration//GEN-END:variables
}
