/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.Ban_DAO;
import DAO.Bill_DAO;
import DAO.CheBien_DAO;
import DAO.Mon_DAO;
import DAO.Nguyenlieu_DAO;
import DAO.Nhanvien_DAO;
import DAO.Order_DAO;
import Lop.Ban;
import Lop.Bill;
import Lop.CheBien;
import Lop.Nguyenlieu;
import Lop.Nhanvien;
import Lop.Order;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_Order extends javax.swing.JFrame {

    /**
     * Creates new form Form_Order
     */
    public static int ban ;
    public static String ma_Bill;
    public Form_Order() {
        initComponents();
        Ban_DAO ban= new Ban_DAO();
        List<Ban> list = ban.selectAll();
        loadTable_ban(list);
        Bill_DAO bill = new Bill_DAO();
        List<Bill> list_bill =bill.selectAll();
        fillTableBill(list_bill);
    }
    private void loadTable_ban(List<Ban> list) {
    DefaultTableModel model = (DefaultTableModel) table_ban.getModel();
    model.setRowCount(0); // clear table
    for (Ban ban : list) {
        model.addRow(new Object[]{ban.getMaban(), ban.getTrangthai()});
    }
}
    private void fillTableBill(List<Bill> list) {
    DefaultTableModel model = (DefaultTableModel) table_bill.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ trước khi đổ mới

    for (Bill b : list) {
        model.addRow(new Object[]{
            b.getMa_Bill(),
            b.getMa_NV(),
            b.getTongGia(),
            b.getBan(),
            b.getDate_Bill(),
            b.getTrangThai()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        panel_ban = new javax.swing.JPanel();
        but_all_ban = new javax.swing.JButton();
        but_bantrong = new javax.swing.JButton();
        txt_search_maban = new javax.swing.JTextField();
        but_search_ban = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_ban = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_maba = new javax.swing.JTextField();
        but_them_ban = new javax.swing.JButton();
        but_xoa_ban = new javax.swing.JButton();
        but_capnhat_ban = new javax.swing.JButton();
        combobox_trangthai_ban = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        combobox_ngay = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combobox_thang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combobox_nam = new javax.swing.JComboBox<>();
        but_bill_chua_thanhtoan = new javax.swing.JButton();
        but_search_theongay = new javax.swing.JButton();
        but_search_theothang = new javax.swing.JButton();
        but_all_bill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_bill = new javax.swing.JTable();
        but_thanhtoan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Label_Ma_Bill = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Label_Ma_NV = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Label_Tongtien = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Label_Ban = new javax.swing.JLabel();
        but_new_bill = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_chon_ban = new javax.swing.JTextField();
        but_odertiep = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jButton1.setBackground(new java.awt.Color(102, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý quán cà phê");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(229, 229, 229)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(202, 202, 202))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        panel_ban.setBackground(new java.awt.Color(255, 255, 204));

        but_all_ban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_all_ban.setText(" Tất cả ");
        but_all_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_all_banActionPerformed(evt);
            }
        });

        but_bantrong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_bantrong.setText("Bàn trống");
        but_bantrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_bantrongActionPerformed(evt);
            }
        });

        txt_search_maban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_mabanActionPerformed(evt);
            }
        });

        but_search_ban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_search_ban.setText("Tìm bàn");
        but_search_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_search_banActionPerformed(evt);
            }
        });

        table_ban.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã bàn", "Trạng thái"
            }
        ));
        table_ban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_banMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ban);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã bàn :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Trạng thái :");

        but_them_ban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_them_ban.setText("Thêm");
        but_them_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_them_banActionPerformed(evt);
            }
        });

        but_xoa_ban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_xoa_ban.setText("Xoá");
        but_xoa_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_xoa_banActionPerformed(evt);
            }
        });

        but_capnhat_ban.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_capnhat_ban.setText("Cập nhật");
        but_capnhat_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_capnhat_banActionPerformed(evt);
            }
        });

        combobox_trangthai_ban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Hết chỗ" }));
        combobox_trangthai_ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_trangthai_banActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_banLayout = new javax.swing.GroupLayout(panel_ban);
        panel_ban.setLayout(panel_banLayout);
        panel_banLayout.setHorizontalGroup(
            panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_banLayout.createSequentialGroup()
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_banLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(but_search_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_banLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(panel_banLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_banLayout.createSequentialGroup()
                                .addComponent(but_all_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(but_bantrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_banLayout.createSequentialGroup()
                                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_maba)
                                    .addComponent(combobox_trangthai_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_banLayout.createSequentialGroup()
                                .addComponent(txt_search_maban, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_banLayout.createSequentialGroup()
                                .addComponent(but_them_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65)
                                .addComponent(but_xoa_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14)))))
                .addGap(13, 13, 13))
            .addGroup(panel_banLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(but_capnhat_ban, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(100, 100, 100))
        );
        panel_banLayout.setVerticalGroup(
            panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_banLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_all_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_bantrong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search_maban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_search_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_maba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combobox_trangthai_ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panel_banLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_them_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(but_xoa_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(but_capnhat_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        combobox_ngay.setMaximumRowCount(32);
        combobox_ngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Ngày :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tháng :");

        combobox_thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Năm :");

        combobox_nam.setModel(new javax.swing.DefaultComboBoxModel<String>(
            java.util.stream.IntStream.rangeClosed(2000, java.time.Year.now().getValue())
            .mapToObj(String::valueOf)
            .toArray(String[]::new)
        )
    );
    combobox_nam.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            combobox_namActionPerformed(evt);
        }
    });

    but_bill_chua_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_bill_chua_thanhtoan.setText("Hoá đơn chưa thanh toán");
    but_bill_chua_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_bill_chua_thanhtoanActionPerformed(evt);
        }
    });

    but_search_theongay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_theongay.setText("Tìm theo ngày");
    but_search_theongay.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_theongayActionPerformed(evt);
        }
    });

    but_search_theothang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_search_theothang.setText("Tìm theo tháng");
    but_search_theothang.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_search_theothangActionPerformed(evt);
        }
    });

    but_all_bill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_all_bill.setText("Tất cả hoá đơn ");
    but_all_bill.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_all_billActionPerformed(evt);
        }
    });

    table_bill.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
        },
        new String [] {
            "Mã hoá đơn", "Mã nhân viên", "Tổng tiền", "Bàn", "Thời gian", "Trạng thái"
        }
    ));
    table_bill.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            table_billMouseClicked(evt);
        }
    });
    jScrollPane2.setViewportView(table_bill);

    but_thanhtoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_thanhtoan.setText("Thanh toán");
    but_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_thanhtoanActionPerformed(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel7.setText("Mã Bill :");

    jLabel8.setBackground(new java.awt.Color(255, 255, 255));

    jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel10.setText("Mã nhân viên :");

    jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel12.setText("Tổng tiền :");

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel14.setText("Bàn :");

    but_new_bill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_new_bill.setText("Gọi món với hoá đơn mới");
    but_new_bill.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_new_billActionPerformed(evt);
        }
    });

    jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel9.setText("Chọn bàn :");

    but_odertiep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    but_odertiep.setText("Gọi món tiếp với hoá đơn này");
    but_odertiep.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            but_odertiepActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(but_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Label_Tongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addComponent(Label_Ma_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label_Ma_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Label_Ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_chon_ban)
                    .addGap(18, 18, 18)
                    .addComponent(but_new_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jScrollPane2)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combobox_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(but_bill_chua_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but_all_bill, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(but_search_theongay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but_search_theothang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(but_odertiep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(combobox_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(combobox_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel6)
                .addComponent(combobox_nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(but_search_theongay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(but_bill_chua_thanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_search_theothang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(but_all_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8)
                .addComponent(Label_Ma_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10)
                .addComponent(Label_Ma_NV))
            .addGap(12, 12, 12)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Label_Tongtien))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Ban)))
            .addGap(18, 18, 18)
            .addComponent(but_thanhtoan)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(but_odertiep)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(but_new_bill)
                .addComponent(jLabel9)
                .addComponent(txt_chon_ban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(21, 21, 21))
    );

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addComponent(panel_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_ban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(0, 0, 0))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(33, 33, 33)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 770, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 632, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_mabanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_mabanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_mabanActionPerformed

    private void but_all_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_all_banActionPerformed
        // TODO add your handling code here:
        Ban_DAO ban= new Ban_DAO();
         List<Ban> list = ban.selectAll();
        loadTable_ban(list);
    }//GEN-LAST:event_but_all_banActionPerformed

    private void but_bantrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_bantrongActionPerformed
        // TODO add your handling code here:
        Ban_DAO ban= new Ban_DAO();
        List<Ban> list = ban.selectAll();
    List<Ban> empty = new ArrayList<>();
    for (Ban b : list) {
        if ("Trống".equalsIgnoreCase(b.getTrangthai())) {
            empty.add(b);
        }
    }
    loadTable_ban(empty);
    }//GEN-LAST:event_but_bantrongActionPerformed

    private void but_search_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_banActionPerformed
        // TODO add your handling code here:
        try {
        int maban = Integer.parseInt(txt_search_maban.getText().trim());
        Ban_DAO banDAO= new Ban_DAO();
        Ban ban = banDAO.selectById(maban);
        if (ban != null) {
            List<Ban> list = new ArrayList<>();
            list.add(ban);
            loadTable_ban(list);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy bàn");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Mã bàn không hợp lệ");
    }
    }//GEN-LAST:event_but_search_banActionPerformed

    private void but_them_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_them_banActionPerformed
        // TODO add your handling code here:
        try {
        int maban = Integer.parseInt(txt_maba.getText().trim());
        String trangthai = (String) combobox_trangthai_ban.getSelectedItem();
        Ban ban = new Ban();
        Ban_DAO banDAO= new Ban_DAO();
        ban.setMaban(maban);
        ban.setTrangthai(trangthai);
        banDAO.insert(ban);
        JOptionPane.showMessageDialog(this, "Thêm bàn thành công");
        but_all_banActionPerformed(null); // refresh table
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi thêm bàn: " + e.getMessage());
    }
    }//GEN-LAST:event_but_them_banActionPerformed

    private void but_xoa_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_xoa_banActionPerformed
        // TODO add your handling code here:
        try {
        int maban = Integer.parseInt(txt_maba.getText().trim());
        Ban_DAO banDAO= new Ban_DAO();
        banDAO.delete(maban);
        JOptionPane.showMessageDialog(this, "Xóa bàn thành công");
        but_all_banActionPerformed(null); // refresh
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi xóa bàn: " + e.getMessage());
    }
    }//GEN-LAST:event_but_xoa_banActionPerformed

    private void but_capnhat_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_capnhat_banActionPerformed
        // TODO add your handling code here:
       try {
        int maBan = Integer.parseInt(txt_maba.getText().trim());
        String trangThai = combobox_trangthai_ban.getSelectedItem().toString();

        Ban ban = new Ban();
        ban.setMaban(maBan);
        ban.setTrangthai(trangThai);
        Ban_DAO banDAO = new Ban_DAO();
        banDAO.update(ban); // Gọi DAO để cập nhật
         Ban_DAO ban1= new Ban_DAO();
        List<Ban> list = ban1.selectAll();
           loadTable_ban(list);
        JOptionPane.showMessageDialog(this, "Cập nhật bàn thành công.");
          
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Mã bàn không hợp lệ.");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật bàn.");
    }
    }//GEN-LAST:event_but_capnhat_banActionPerformed

    private void combobox_trangthai_banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_trangthai_banActionPerformed
        // TODO add your handling code here:
         try {
        int maban = Integer.parseInt(txt_maba.getText().trim());
        String trangthai = (String) combobox_trangthai_ban.getSelectedItem();
        Ban ban = new Ban();
        ban.setMaban(maban);
        ban.setTrangthai(trangthai);
        Ban_DAO banDAO= new Ban_DAO();
        banDAO.update(ban);
        
        but_all_banActionPerformed(null);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi cập nhật: " + e.getMessage());
    }
    }//GEN-LAST:event_combobox_trangthai_banActionPerformed

    private void but_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_thanhtoanActionPerformed
        // TODO add your handling code here:
        try {
        // 1. Lấy mã hóa đơn từ label
        String ma_Bill = Label_Ma_Bill.getText().trim();

        if (ma_Bill.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có hóa đơn được chọn.");
            return;
        }

        // 2. Lấy thông tin hóa đơn
        Bill_DAO billDao = new Bill_DAO();
        Bill bill = billDao.selectById(ma_Bill);

        if (bill == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn.");
            return;
        }

        // 3. Kiểm tra hóa đơn đã thanh toán chưa
        if (bill.getTrangThai().equalsIgnoreCase("Đã thanh toán")) {
            Bill_DAO bill1 = new Bill_DAO();
        List<Bill> list_bill =bill1.selectAll();
        fillTableBill(list_bill);
            JOptionPane.showMessageDialog(this, "Hóa đơn đã được thanh toán.");
            return;
        }

        // 4. Cập nhật trạng thái hóa đơn
        bill.setTrangThai("Đã thanh toán");
        bill.setDate_Bill(new java.sql.Timestamp(System.currentTimeMillis())); // cập nhật thời gian thanh toán
        billDao.update(bill);

        // 5. Đổi trạng thái bàn về "Trống"
        Ban_DAO banDao = new Ban_DAO();
        Ban ban = banDao.selectById(bill.getBan());
        if (ban != null) {
            ban.setTrangthai("Trống");
            banDao.update(ban);
        }
        Order_DAO orderDao = new Order_DAO();
    CheBien_DAO cheBienDao = new CheBien_DAO();
    Nguyenlieu_DAO nglieuDao = new Nguyenlieu_DAO();

    // Lấy danh sách món đã gọi trong hóa đơn
    List<Order> danhSachMon = orderDao.selectByMaBill(ma_Bill);

    // Duyệt từng món ăn
    for (Order order : danhSachMon) {
        String maMon = order.getMa_Mon();
        int soLuongMon = order.getSL_order();

    // Lấy danh sách nguyên liệu cần cho món này
    List<CheBien> congThuc = cheBienDao.selectByMaMon(maMon);

    for (CheBien cb : congThuc) {
        String maNgLieu = cb.getMa_Nglieu();
        double slCanCho1Mon = cb.getSL_chebien();

        double tongSLCan = slCanCho1Mon * soLuongMon;

        // Trừ số lượng nguyên liệu trong kho
        Nguyenlieu ngl = nglieuDao.selectById(maNgLieu);
        if (ngl != null) {
            double slHienTai = ngl.getSL_NL();
            double slConLai = slHienTai - tongSLCan;
            if (slConLai < 0) slConLai = 0;

            ngl.setSL_NL(slConLai);
            nglieuDao.update(ngl);
        }
    }
}

        // 6. Thông báo và làm mới giao diện
        
        JOptionPane.showMessageDialog(this, "Thanh toán thành công!");
        Ban_DAO ban2= new Ban_DAO();
        List<Ban> list = ban2.selectAll();
        loadTable_ban(list);
        // load lại bảng hoặc chuyển về trạng thái ban đầu nếu cần:
        // fillTable();  // nếu bạn có hàm load lại table
        // resetFields(); // nếu cần reset các trường nhập

        // 7. Ghi hóa đơn vào file cố định (xóa dữ liệu cũ)
    
        String fileName = "hoadon.txt";
        FileWriter writer = new FileWriter(fileName); // không có 'true' nghĩa là ghi đè
        BufferedWriter bw = new BufferedWriter(writer);

        bw.write("======= HÓA ĐƠN THANH TOÁN =======\n");
        bw.write("Mã Hóa Đơn: " + bill.getMa_Bill() + "\n");
        bw.write("Bàn: " + bill.getBan() + "\n");
        bw.write("Thời gian: " + bill.getDate_Bill() + "\n");
        bw.write("----------------------------------\n");
        bw.write(String.format("%-20s %-10s %-10s %-10s\n", "Tên Món", "SL", "Đơn giá", "Thành tiền"));

        
        Mon_DAO monAnDao = new Mon_DAO(); // cần class này
        List<Order> orders = orderDao.selectByMaBill(ma_Bill);
        double tongTien = 0;

        for (Order order : orders) {
            String tenMon = monAnDao.selectByMa_Mon(order.getMa_Mon()).getTen_Mon(); // cần class MonAn_DAO
            int sl = order.getSL_order();
            double donGia = order.getGia_Mon();
            double thanhTien = order.gettonggia_order();
            tongTien += thanhTien;
            bw.write(String.format("%-20s %-10d %-10.2f %-10.2f\n", tenMon, sl, donGia, thanhTien));
        }

        bw.write("----------------------------------\n");
        bw.write(String.format("TỔNG CỘNG: %.2f VND\n", tongTien));
        bw.write("Trạng thái: " + bill.getTrangThai() + "\n");
        bw.write("==================================\n");

        bw.close();
        
        fillTableBill(billDao.selectAll());

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thanh toán hóa đơn!");
    }
    }//GEN-LAST:event_but_thanhtoanActionPerformed
    
    private void combobox_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox_namActionPerformed

    private void but_new_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_new_billActionPerformed
        // TODO add your handling code here:
      try {
        // 1. Lấy số bàn
        String soBanText = txt_chon_ban.getText().trim();
        if (soBanText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số bàn!");
            return;
        }

        int soBan = Integer.parseInt(soBanText);

        // 2. Kiểm tra bàn có trống không
        Ban_DAO banDao = new Ban_DAO();
        Ban ban = banDao.selectById(soBan);

        if (ban == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy bàn!");
            return;
        }

        if (!ban.getTrangthai().equalsIgnoreCase("Trống")) {
            JOptionPane.showMessageDialog(this, "Bàn đã có người sử dụng!");
            return;
        }

        // 3. Lấy nhân viên hiện tại
        String currentUser = Form_login.currentUser;
        if (currentUser == null || currentUser.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không xác định được người dùng hiện tại.");
            return;
        }

        Nhanvien_DAO nvDao = new Nhanvien_DAO();
        Nhanvien nv = nvDao.SelectByUser(currentUser);
        if (nv == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin nhân viên.");
            return;
        }

        // 4. Tạo mã hóa đơn theo thời gian + random
        String timeStr = new SimpleDateFormat("yyyyMMddHHmmss").format(new Date());
        String randomStr = String.format("%04d", new Random().nextInt(1000000));
         ma_Bill = "HD" + timeStr + randomStr;

        // 5. Tạo hóa đơn mới
        Bill bill = new Bill();
        bill.setMa_Bill(ma_Bill);
        bill.setBan(soBan);
        bill.setMa_NV(nv.getMa_NV());
        bill.setTrangThai("Chưa thanh toán");

        // Thời gian hiện tại
        bill.setDate_Bill(new java.sql.Timestamp(System.currentTimeMillis()));

        // 6. Lưu vào CSDL
        Bill_DAO billDao = new Bill_DAO();
        billDao.insert(bill);

        // 7. Đổi trạng thái bàn sang "Đang sử dụng"
        ban.setTrangthai("Đang sử dụng");
        banDao.update(ban);

        // 8. Mở form gọi món
        Form_Goi formGoi = new Form_Goi(); // truyền mã bill nếu cần
        formGoi.setVisible(true);
        this.dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Số bàn không hợp lệ!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi tạo hóa đơn mới!");
    }
    }//GEN-LAST:event_but_new_billActionPerformed

    private void but_search_theongayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_theongayActionPerformed
        // TODO add your handling code here:
         try {
        int ngay = Integer.parseInt(combobox_ngay.getSelectedItem().toString());
        int thang = Integer.parseInt(combobox_thang.getSelectedItem().toString()) - 1; // Tháng trong Java bắt đầu từ 0
        int nam = Integer.parseInt(combobox_nam.getSelectedItem().toString());

        Calendar calendar = Calendar.getInstance();
        calendar.set(nam, thang, ngay);
        java.util.Date date = calendar.getTime();

        Bill_DAO dao = new Bill_DAO();
        List<Bill> list = dao.selectByDate(date);
        fillTableBill(list); // Phương thức đổ dữ liệu ra bảng

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày hợp lệ!");
    }
    }//GEN-LAST:event_but_search_theongayActionPerformed

    private void but_search_theothangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_theothangActionPerformed
        // TODO add your handling code here:
         try {
        int thang = Integer.parseInt((String) combobox_thang.getSelectedItem());
        int nam = Integer.parseInt((String) combobox_nam.getSelectedItem());

        Bill_DAO dao = new Bill_DAO();
        List<Bill> list = dao.selectByMonth(thang, nam);

        fillTableBill(list); // gọi hàm fill bảng
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn tháng và năm hợp lệ!");
    }
    }//GEN-LAST:event_but_search_theothangActionPerformed

    private void but_all_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_all_billActionPerformed
        // TODO add your handling code here:
     Bill_DAO dao = new Bill_DAO();
    List<Bill> list = dao.selectAll();
    fillTableBill(list);
    }//GEN-LAST:event_but_all_billActionPerformed

    private void but_bill_chua_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_bill_chua_thanhtoanActionPerformed
        // TODO add your handling code here:
        Bill_DAO dao = new Bill_DAO();
    List<Bill> list = dao.selectByStatus("Chưa thanh toán");
    fillTableBill(list);
    }//GEN-LAST:event_but_bill_chua_thanhtoanActionPerformed

    private void table_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_billMouseClicked
        // TODO add your handling code here:
        int row = table_bill.getSelectedRow();
        if (row >= 0) {
            Label_Ban.setText(table_bill.getValueAt(row, 3).toString());
            Label_Ma_Bill.setText(table_bill.getValueAt(row, 0).toString());
            Label_Ma_NV.setText(table_bill.getValueAt(row, 1).toString());
            Label_Tongtien.setText(table_bill.getValueAt(row, 2).toString());
         }
    }//GEN-LAST:event_table_billMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if (Form_login.role==1) {
                    // Admin login
                    
                    Form_Main nv = new Form_Main();
                    nv.setVisible(true);
                    this.dispose();
                } else {
                    // Nhân viên login
                
                    Form_MainNV nv = new Form_MainNV();
                    nv.setVisible(true);
                    this.dispose();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void table_banMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_banMouseClicked
        // TODO add your handling code here:
        int row = table_ban.getSelectedRow(); // Sửa lại đúng bảng
    if (row >= 0) {
        txt_maba.setText(table_ban.getValueAt(row, 0).toString());
        combobox_trangthai_ban.setSelectedItem(table_ban.getValueAt(row, 1).toString());
    }
    }//GEN-LAST:event_table_banMouseClicked

    private void but_odertiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_odertiepActionPerformed
        // TODO add your handling code here:
        try {
     ma_Bill = Label_Ma_Bill.getText();

    // Lấy thông tin nhân viên hiện tại
    Nhanvien_DAO dao = new Nhanvien_DAO();
    String currentUser = Form_login.currentUser;
    Nhanvien nv = dao.SelectByUser(currentUser);

    // Lấy hóa đơn theo mã
    Bill_DAO bill_dao = new Bill_DAO();
    Bill bill = bill_dao.selectById(ma_Bill);

    if (bill == null) {
        JOptionPane.showMessageDialog(this, "Không tìm thấy hóa đơn.");
        return;
    }

    // Kiểm tra trạng thái hóa đơn
    if (!bill.getTrangThai().equalsIgnoreCase("Chưa thanh toán")) {
        JOptionPane.showMessageDialog(this, "Hóa đơn đã thanh toán, không thể gọi thêm!");
        return;
    }

    // Cập nhật nhân viên phụ trách
    bill.setMa_NV(nv.getMa_NV());
    bill_dao.update(bill);

    // Mở Form gọi món
    Form_Goi n = new Form_Goi();
    n.setVisible(true);
    this.dispose();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Lỗi khi xử lý hóa đơn!");
}
    }//GEN-LAST:event_but_odertiepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Ban;
    private javax.swing.JLabel Label_Ma_Bill;
    private javax.swing.JLabel Label_Ma_NV;
    private javax.swing.JLabel Label_Tongtien;
    private javax.swing.JButton but_all_ban;
    private javax.swing.JButton but_all_bill;
    private javax.swing.JButton but_bantrong;
    private javax.swing.JButton but_bill_chua_thanhtoan;
    private javax.swing.JButton but_capnhat_ban;
    private javax.swing.JButton but_new_bill;
    private javax.swing.JButton but_odertiep;
    private javax.swing.JButton but_search_ban;
    private javax.swing.JButton but_search_theongay;
    private javax.swing.JButton but_search_theothang;
    private javax.swing.JButton but_thanhtoan;
    private javax.swing.JButton but_them_ban;
    private javax.swing.JButton but_xoa_ban;
    private javax.swing.JComboBox<String> combobox_nam;
    private javax.swing.JComboBox<String> combobox_ngay;
    private javax.swing.JComboBox<String> combobox_thang;
    private javax.swing.JComboBox<String> combobox_trangthai_ban;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_ban;
    private javax.swing.JTable table_ban;
    private javax.swing.JTable table_bill;
    private javax.swing.JTextField txt_chon_ban;
    private javax.swing.JTextField txt_maba;
    private javax.swing.JTextField txt_search_maban;
    // End of variables declaration//GEN-END:variables
}
