/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import DAO.Bill_DAO;
import DAO.CheBien_DAO;
import DAO.Mon_DAO;
import DAO.Nguyenlieu_DAO;
import DAO.Order_DAO;
import Lop.Bill;
import Lop.CheBien;
import Lop.Mon;
import Lop.Order;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_Goi extends javax.swing.JFrame {

    /**
     * Creates new form Form_Goi
     */
    public Form_Goi() {
        initComponents();
        loadTableMon();
        loadTable_OrderBill();
        Label_Mabill.setText(Form_Order.ma_Bill);
    }
public void loadTableMon() {
    Mon_DAO dao = new Mon_DAO();
    List<Mon> list = dao.selectAll();
    DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
    model.setRowCount(0);
    for (Mon mon : list) {
        model.addRow(new Object[]{
            mon.getMa_Mon(), mon.getTen_Mon(), mon.getGia_Mon(), mon.getMa_LM(), mon.getHinhanh()
        });
    }
}
public void loadTable_OrderBill() {
    DefaultTableModel model = (DefaultTableModel) table_oder_bill.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ nếu có

    String mabill = Form.Form_Order.ma_Bill; // Lấy mã bill từ label

    Order_DAO orderDAO = new Order_DAO();
    List<Order> dsOrder = orderDAO.selectByMaBill(mabill); // Hàm này bạn cần viết trong DAO

    for (Order order : dsOrder) {
        Object[] row = {
            order.getMa_Bill(),
            order.getMa_Mon(),
            order.getGia_Mon(),
            order.getSL_order(),
            order.gettonggia_order()
        };
        model.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        but_back = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_oder_bill = new javax.swing.JTable();
        but_luu = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_mon = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        but_timloaimon = new javax.swing.JButton();
        but_search_mamon = new javax.swing.JButton();
        txt_search_maloai = new javax.swing.JTextField();
        txt_search_mamon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Label_tenmon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Label_gia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        Label_thanhtien = new javax.swing.JLabel();
        label_hinhanh = new javax.swing.JLabel();
        but_add_mon_vao_bill = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Label_Mabill = new javax.swing.JLabel();
        but_tim_all = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        but_chinhsua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Gọi món");

        but_back.setBackground(new java.awt.Color(102, 255, 255));
        but_back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        but_back.setText("Back");
        but_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_backActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        table_oder_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Mã món", "Giá", "Số lượng ", "Thành tiền"
            }
        ));
        table_oder_bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_oder_billMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_oder_bill);

        but_luu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        but_luu.setText("Lưu");
        but_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_luuActionPerformed(evt);
            }
        });

        table_mon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã món", "Tên món", "Giá", "Loại món", "Hình ảnh"
            }
        ));
        table_mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_monMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_mon);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã loại :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Mã món : ");

        but_timloaimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_timloaimon.setText("Tìm loại");
        but_timloaimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_timloaimonActionPerformed(evt);
            }
        });

        but_search_mamon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_search_mamon.setText("Tìm món");
        but_search_mamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_search_mamonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mã món :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giá :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng :");

        txt_soluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soluongActionPerformed(evt);
            }
        });

        label_hinhanh.setText("Hình ảnh");

        but_add_mon_vao_bill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_add_mon_vao_bill.setText("Lưu món ");
        but_add_mon_vao_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_add_mon_vao_billActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mã hoá đơn :");

        but_tim_all.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_tim_all.setText("Tìm tất cả");
        but_tim_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_tim_allActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Thành tiền :");

        but_chinhsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        but_chinhsua.setText("Lưu chỉnh sửa");
        but_chinhsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_chinhsuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_Mabill, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(but_luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(179, 179, 179))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_search_mamon)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txt_search_maloai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(but_timloaimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(7, 7, 7)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(but_search_mamon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(but_tim_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_soluong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Label_gia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Label_thanhtien, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addGap(7, 7, 7)))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(label_hinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(82, 82, 82)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(but_chinhsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(but_add_mon_vao_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(but_timloaimon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txt_search_maloai))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(but_tim_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(but_search_mamon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txt_search_mamon)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(Label_tenmon)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_gia)
                    .addComponent(Label_Mabill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txt_soluong)
                    .addComponent(Label_thanhtien)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(but_add_mon_vao_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(but_chinhsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(but_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_hinhanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(but_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(275, 275, 275)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(401, 401, 401))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(but_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_luuActionPerformed
                String mabill = Form_Order.ma_Bill;
          Bill_DAO billdao = new Bill_DAO();
          Order_DAO orderdao = new Order_DAO();

          Bill bill = billdao.selectById(mabill);
          if (bill == null) {
              bill = new Bill();
              bill.setMa_Bill(mabill); // nếu cần thiết
          }

          bill.setTongGia(orderdao.tinhTongThanhTien(mabill));
          billdao.update(bill);
          loadTable_OrderBill();
          

          Form_Order nv = new Form_Order();
          nv.setVisible(true);
          this.dispose();

    }//GEN-LAST:event_but_luuActionPerformed

    private void table_monMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_monMouseClicked
        // TODO add your handling code here:
        int row = table_mon.getSelectedRow();
        if (row >= 0) {
            Label_tenmon.setText(table_mon.getValueAt(row, 0).toString());
            Label_gia.setText(table_mon.getValueAt(row, 2).toString());
         
            ImageIcon icon = new ImageIcon(table_mon.getValueAt(row, 4).toString());

        // Resize ảnh cho vừa JLabel
        Image img = icon.getImage();
        Image scaledImg = img.getScaledInstance(label_hinhanh.getWidth(), label_hinhanh.getHeight(), Image.SCALE_SMOOTH);
        label_hinhanh.setIcon(new ImageIcon(scaledImg));
        }
    }//GEN-LAST:event_table_monMouseClicked

    private void but_timloaimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_timloaimonActionPerformed
        // TODO add your handling code here:
        String maMon = txt_search_maloai.getText().trim();
        if (maMon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã loại để tìm!");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
        model.setRowCount(0); // Xóa dòng cũ

        Mon_DAO dao = new Mon_DAO();
        List<Mon> list = dao.selectByMaLoai(maMon);

        for (Mon m : list) {
            Object[] row = new Object[] {
                m.getMa_Mon(),
                m.getTen_Mon(),
                m.getGia_Mon(),
                m.getMa_LM(),
                m.getHinhanh()
            };
            model.addRow(row);
        }
    }//GEN-LAST:event_but_timloaimonActionPerformed

    private void but_search_mamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_search_mamonActionPerformed
        // TODO add your handling code here:
        String maMon = txt_search_mamon.getText().trim();
        if (maMon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã món để tìm!");
            return;
        }

        Mon_DAO dao = new Mon_DAO();
        Mon mon = dao.selectByMa_Mon(maMon);

        DefaultTableModel model = (DefaultTableModel) table_mon.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        if (mon != null) {
            model.addRow(new Object[]{
                mon.getMa_Mon(),
                mon.getTen_Mon(),
                mon.getGia_Mon(),
                mon.getMa_LM(),
                mon.getHinhanh()
            });
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy món!");
        }
    }//GEN-LAST:event_but_search_mamonActionPerformed

    private void txt_soluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soluongActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_soluongActionPerformed

    private void but_add_mon_vao_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_add_mon_vao_billActionPerformed
         try {
        String mabill = Form_Order.ma_Bill;
        String mamon = Label_tenmon.getText().trim();  // Dùng Ma_Mon nếu có
        int soluong = Integer.parseInt(txt_soluong.getText().trim());
        double gia = Double.parseDouble(Label_gia.getText().trim());
        double thanhtien = soluong * gia;

        if (soluong <= 0) {
            JOptionPane.showMessageDialog(null, "Làm ơn nhập số lượng lớn hơn 0!");
            return;
        }

        // 1. Kiểm tra tồn kho nguyên liệu
        CheBien_DAO cheBienDAO = new CheBien_DAO();
        Nguyenlieu_DAO nguyenLieuDAO = new Nguyenlieu_DAO(); // Bạn phải có DAO này

        List<CheBien> dsNgLieu = cheBienDAO.selectByMaMon(mamon);
        for (CheBien cb : dsNgLieu) {
            double sl_can = cb.getSL_chebien() * soluong;
            int sl_ton = nguyenLieuDAO.getSoLuongTon(cb.getMa_Nglieu()); // Bạn phải viết hàm này

            if (sl_ton < sl_can) {
                JOptionPane.showMessageDialog(null,
                    "Nguyên liệu \"" + cb.getMa_Nglieu() + "\" không đủ trong kho!\nCần: " + sl_can + ", Hiện có: " + sl_ton);
                return;
            }
        }

        // 2. Nếu đủ: Thêm vào bill
        Order order = new Order();
        order.setMa_Bill(mabill);
        order.setMa_Mon(mamon);
        order.setSL_order(soluong);
        order.setGia_Mon(gia);
        order.settonggia_order(thanhtien);

        Order_DAO orderdao = new Order_DAO();
        orderdao.insert(order); 

        loadTable_OrderBill(); // Cập nhật bảng bill
        JOptionPane.showMessageDialog(null, "Đã cập nhật món vào bill!");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng hợp lệ!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi xử lý món!");
    }
    }//GEN-LAST:event_but_add_mon_vao_billActionPerformed

    private void but_tim_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_tim_allActionPerformed
        // TODO add your handling code here:
        loadTableMon();
    }//GEN-LAST:event_but_tim_allActionPerformed

    private void table_oder_billMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_oder_billMouseClicked
        // TODO add your handling code here:
         int row = table_oder_bill.getSelectedRow();
    if (row >= 0) {
        // Hiển thị thông tin món lên các label và input
        Label_Mabill.setText(table_oder_bill.getValueAt(row, 0).toString());
        Label_tenmon.setText(table_oder_bill.getValueAt(row, 1).toString());
        // Nếu bạn cần mã món, có thể lấy từ cột 2 (nếu có)
        txt_soluong.setText(table_oder_bill.getValueAt(row, 3).toString());
        Label_gia.setText(table_oder_bill.getValueAt(row, 4).toString());
        Label_thanhtien.setText(table_oder_bill.getValueAt(row, 5).toString());
        
    }
    }//GEN-LAST:event_table_oder_billMouseClicked

    private void but_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_backActionPerformed
        // TODO add your handling code here:\
                  
                    Form_Order nv = new Form_Order();
                    nv.setVisible(true);
                    this.dispose();
               
    }//GEN-LAST:event_but_backActionPerformed

    private void but_chinhsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_chinhsuaActionPerformed
         try {
        String mabill = Form_Order.ma_Bill;
        String mamon = Label_tenmon.getText().trim();  // Bạn đang dùng tên làm mã — nên đổi nếu có Ma_Mon thật
        int soluong = Integer.parseInt(txt_soluong.getText().trim());
        double gia = Double.parseDouble(Label_gia.getText().trim());
        double thanhtien = soluong * gia;

        Order_DAO orderdao = new Order_DAO();

        if (soluong == 0) {
            // Nếu số lượng = 0 thì xóa món khỏi bill
            orderdao.delete(mabill, mamon);
            JOptionPane.showMessageDialog(null, "Đã xóa món khỏi bill!");
        } else {
            // Ngược lại: cập nhật món vào bill
            Order order = new Order();
            order.setMa_Bill(mabill);
            order.setMa_Mon(mamon);
            order.setSL_order(soluong);
            order.setGia_Mon(gia);
            order.settonggia_order(thanhtien);

            orderdao.update(order); 
            loadTable_OrderBill();// bạn có thể gọi update luôn nếu món đã có sẵn
            JOptionPane.showMessageDialog(null, "Đã cập nhật món vào bill!");
        }

        // Load lại bảng hóa đơn nếu cần
        // loadTableOrderBill(mabill);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập số lượng hợp lệ!");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi xử lý món!");
    }
        
    }//GEN-LAST:event_but_chinhsuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Goi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Goi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Goi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Goi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Goi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Mabill;
    private javax.swing.JLabel Label_gia;
    private javax.swing.JLabel Label_tenmon;
    private javax.swing.JLabel Label_thanhtien;
    private javax.swing.JButton but_add_mon_vao_bill;
    private javax.swing.JButton but_back;
    private javax.swing.JButton but_chinhsua;
    private javax.swing.JButton but_luu;
    private javax.swing.JButton but_search_mamon;
    private javax.swing.JButton but_tim_all;
    private javax.swing.JButton but_timloaimon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_hinhanh;
    private javax.swing.JTable table_mon;
    private javax.swing.JTable table_oder_bill;
    private javax.swing.JTextField txt_search_maloai;
    private javax.swing.JTextField txt_search_mamon;
    private javax.swing.JTextField txt_soluong;
    // End of variables declaration//GEN-END:variables
}
