# Generated by Django 4.2 on 2025-11-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_alter_menuitem_options_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='category',
            table='menu_category',
        ),
    ]
